window.esdocSearchIndex = [
  [
    "typhonjs-escomplex-commons/src/module/report/abstractreport.js~abstractreport",
    "class/src/module/report/AbstractReport.js~AbstractReport.html",
    "<span>AbstractReport</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/module/report/AbstractReport.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex-commons/src/module/plugin/syntax/abstractsyntaxloader.js~abstractsyntaxloader",
    "class/src/module/plugin/syntax/AbstractSyntaxLoader.js~AbstractSyntaxLoader.html",
    "<span>AbstractSyntaxLoader</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/module/plugin/syntax/AbstractSyntaxLoader.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex-commons/src/module/report/classreport.js~classreport",
    "class/src/module/report/ClassReport.js~ClassReport.html",
    "<span>ClassReport</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/module/report/ClassReport.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex-commons/src/module/traits/halsteadarray.js~halsteadarray",
    "class/src/module/traits/HalsteadArray.js~HalsteadArray.html",
    "<span>HalsteadArray</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/module/traits/HalsteadArray.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex-commons/src/module/report/halsteaddata.js~halsteaddata",
    "class/src/module/report/HalsteadData.js~HalsteadData.html",
    "<span>HalsteadData</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/module/report/HalsteadData.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex-commons/src/utils/mathutil.js~mathutil",
    "class/src/utils/MathUtil.js~MathUtil.html",
    "<span>MathUtil</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/utils/MathUtil.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex-commons/src/module/report/methodreport.js~methodreport",
    "class/src/module/report/MethodReport.js~MethodReport.html",
    "<span>MethodReport</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/module/report/MethodReport.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex-commons/src/module/report/modulereport.js~modulereport",
    "class/src/module/report/ModuleReport.js~ModuleReport.html",
    "<span>ModuleReport</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/module/report/ModuleReport.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex-commons/src/project/result/projectresult.js~projectresult",
    "class/src/project/result/ProjectResult.js~ProjectResult.html",
    "<span>ProjectResult</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/project/result/ProjectResult.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex-commons/src/utils/stringutil.js~stringutil",
    "class/src/utils/StringUtil.js~StringUtil.html",
    "<span>StringUtil</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/utils/StringUtil.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex-commons/src/module/traits/trait.js~trait",
    "class/src/module/traits/Trait.js~Trait.html",
    "<span>Trait</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/module/traits/Trait.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex-commons/src/module/traits/traithalstead.js~traithalstead",
    "class/src/module/traits/TraitHalstead.js~TraitHalstead.html",
    "<span>TraitHalstead</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/module/traits/TraitHalstead.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex-commons/src/module/traits/actualize.js~actualize",
    "function/index.html#static-function-actualize",
    "<span>actualize</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/module/traits/actualize.js</span>",
    "function"
  ],
  [
    "typhonjs-escomplex-commons/src/module/traits/safearray.js~safearray",
    "function/index.html#static-function-safeArray",
    "<span>safeArray</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/module/traits/safeArray.js</span>",
    "function"
  ],
  [
    "typhonjs-escomplex-commons/src/module/traits/safename.js~safename",
    "function/index.html#static-function-safeName",
    "<span>safeName</span> <span class=\"search-result-import-path\">typhonjs-escomplex-commons/src/module/traits/safeName.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/module/plugin/syntax/abstractsyntaxloader.js",
    "file/src/module/plugin/syntax/AbstractSyntaxLoader.js.html",
    "src/module/plugin/syntax/AbstractSyntaxLoader.js",
    "file"
  ],
  [
    "src/module/plugin/syntax/abstractsyntaxloader.js~abstractsyntaxloader#onloadsyntax",
    "class/src/module/plugin/syntax/AbstractSyntaxLoader.js~AbstractSyntaxLoader.html#instance-method-onLoadSyntax",
    "src/module/plugin/syntax/AbstractSyntaxLoader.js~AbstractSyntaxLoader#onLoadSyntax",
    "method"
  ],
  [
    "src/module/report/abstractreport.js",
    "file/src/module/report/AbstractReport.js.html",
    "src/module/report/AbstractReport.js",
    "file"
  ],
  [
    "src/module/report/abstractreport.js~abstractreport#_methodreport",
    "class/src/module/report/AbstractReport.js~AbstractReport.html#instance-member-_methodReport",
    "src/module/report/AbstractReport.js~AbstractReport#_methodReport",
    "member"
  ],
  [
    "src/module/report/abstractreport.js~abstractreport#constructor",
    "class/src/module/report/AbstractReport.js~AbstractReport.html#instance-constructor-constructor",
    "src/module/report/AbstractReport.js~AbstractReport#constructor",
    "method"
  ],
  [
    "src/module/report/abstractreport.js~abstractreport#finalize",
    "class/src/module/report/AbstractReport.js~AbstractReport.html#instance-method-finalize",
    "src/module/report/AbstractReport.js~AbstractReport#finalize",
    "method"
  ],
  [
    "src/module/report/abstractreport.js~abstractreport#incrementdistincthalsteaditems",
    "class/src/module/report/AbstractReport.js~AbstractReport.html#instance-method-incrementDistinctHalsteadItems",
    "src/module/report/AbstractReport.js~AbstractReport#incrementDistinctHalsteadItems",
    "method"
  ],
  [
    "src/module/report/abstractreport.js~abstractreport#incrementhalsteaditems",
    "class/src/module/report/AbstractReport.js~AbstractReport.html#instance-method-incrementHalsteadItems",
    "src/module/report/AbstractReport.js~AbstractReport#incrementHalsteadItems",
    "method"
  ],
  [
    "src/module/report/abstractreport.js~abstractreport#incrementhalsteadmetric",
    "class/src/module/report/AbstractReport.js~AbstractReport.html#instance-method-incrementHalsteadMetric",
    "src/module/report/AbstractReport.js~AbstractReport#incrementHalsteadMetric",
    "method"
  ],
  [
    "src/module/report/abstractreport.js~abstractreport#incrementparams",
    "class/src/module/report/AbstractReport.js~AbstractReport.html#instance-method-incrementParams",
    "src/module/report/AbstractReport.js~AbstractReport#incrementParams",
    "method"
  ],
  [
    "src/module/report/abstractreport.js~abstractreport#ishalsteadmetricdistinct",
    "class/src/module/report/AbstractReport.js~AbstractReport.html#instance-method-isHalsteadMetricDistinct",
    "src/module/report/AbstractReport.js~AbstractReport#isHalsteadMetricDistinct",
    "method"
  ],
  [
    "src/module/report/abstractreport.js~abstractreport#methodreport",
    "class/src/module/report/AbstractReport.js~AbstractReport.html#instance-get-methodReport",
    "src/module/report/AbstractReport.js~AbstractReport#methodReport",
    "member"
  ],
  [
    "src/module/report/classreport.js",
    "file/src/module/report/ClassReport.js.html",
    "src/module/report/ClassReport.js",
    "file"
  ],
  [
    "src/module/report/classreport.js~classreport#aggregate",
    "class/src/module/report/ClassReport.js~ClassReport.html#instance-member-aggregate",
    "src/module/report/ClassReport.js~ClassReport#aggregate",
    "member"
  ],
  [
    "src/module/report/classreport.js~classreport#constructor",
    "class/src/module/report/ClassReport.js~ClassReport.html#instance-constructor-constructor",
    "src/module/report/ClassReport.js~ClassReport#constructor",
    "method"
  ],
  [
    "src/module/report/classreport.js~classreport#finalize",
    "class/src/module/report/ClassReport.js~ClassReport.html#instance-method-finalize",
    "src/module/report/ClassReport.js~ClassReport#finalize",
    "method"
  ],
  [
    "src/module/report/classreport.js~classreport#lineend",
    "class/src/module/report/ClassReport.js~ClassReport.html#instance-member-lineEnd",
    "src/module/report/ClassReport.js~ClassReport#lineEnd",
    "member"
  ],
  [
    "src/module/report/classreport.js~classreport#linestart",
    "class/src/module/report/ClassReport.js~ClassReport.html#instance-member-lineStart",
    "src/module/report/ClassReport.js~ClassReport#lineStart",
    "member"
  ],
  [
    "src/module/report/classreport.js~classreport#methods",
    "class/src/module/report/ClassReport.js~ClassReport.html#instance-member-methods",
    "src/module/report/ClassReport.js~ClassReport#methods",
    "member"
  ],
  [
    "src/module/report/classreport.js~classreport#name",
    "class/src/module/report/ClassReport.js~ClassReport.html#instance-member-name",
    "src/module/report/ClassReport.js~ClassReport#name",
    "member"
  ],
  [
    "src/module/report/classreport.js~classreport.parse",
    "class/src/module/report/ClassReport.js~ClassReport.html#static-method-parse",
    "src/module/report/ClassReport.js~ClassReport.parse",
    "method"
  ],
  [
    "src/module/report/halsteaddata.js",
    "file/src/module/report/HalsteadData.js.html",
    "src/module/report/HalsteadData.js",
    "file"
  ],
  [
    "src/module/report/halsteaddata.js~halsteaddata#bugs",
    "class/src/module/report/HalsteadData.js~HalsteadData.html#instance-member-bugs",
    "src/module/report/HalsteadData.js~HalsteadData#bugs",
    "member"
  ],
  [
    "src/module/report/halsteaddata.js~halsteaddata#constructor",
    "class/src/module/report/HalsteadData.js~HalsteadData.html#instance-constructor-constructor",
    "src/module/report/HalsteadData.js~HalsteadData#constructor",
    "method"
  ],
  [
    "src/module/report/halsteaddata.js~halsteaddata#difficulty",
    "class/src/module/report/HalsteadData.js~HalsteadData.html#instance-member-difficulty",
    "src/module/report/HalsteadData.js~HalsteadData#difficulty",
    "member"
  ],
  [
    "src/module/report/halsteaddata.js~halsteaddata#effort",
    "class/src/module/report/HalsteadData.js~HalsteadData.html#instance-member-effort",
    "src/module/report/HalsteadData.js~HalsteadData#effort",
    "member"
  ],
  [
    "src/module/report/halsteaddata.js~halsteaddata#length",
    "class/src/module/report/HalsteadData.js~HalsteadData.html#instance-member-length",
    "src/module/report/HalsteadData.js~HalsteadData#length",
    "member"
  ],
  [
    "src/module/report/halsteaddata.js~halsteaddata#operands",
    "class/src/module/report/HalsteadData.js~HalsteadData.html#instance-member-operands",
    "src/module/report/HalsteadData.js~HalsteadData#operands",
    "member"
  ],
  [
    "src/module/report/halsteaddata.js~halsteaddata#operators",
    "class/src/module/report/HalsteadData.js~HalsteadData.html#instance-member-operators",
    "src/module/report/HalsteadData.js~HalsteadData#operators",
    "member"
  ],
  [
    "src/module/report/halsteaddata.js~halsteaddata#reset",
    "class/src/module/report/HalsteadData.js~HalsteadData.html#instance-method-reset",
    "src/module/report/HalsteadData.js~HalsteadData#reset",
    "method"
  ],
  [
    "src/module/report/halsteaddata.js~halsteaddata#time",
    "class/src/module/report/HalsteadData.js~HalsteadData.html#instance-member-time",
    "src/module/report/HalsteadData.js~HalsteadData#time",
    "member"
  ],
  [
    "src/module/report/halsteaddata.js~halsteaddata#vocabulary",
    "class/src/module/report/HalsteadData.js~HalsteadData.html#instance-member-vocabulary",
    "src/module/report/HalsteadData.js~HalsteadData#vocabulary",
    "member"
  ],
  [
    "src/module/report/halsteaddata.js~halsteaddata#volume",
    "class/src/module/report/HalsteadData.js~HalsteadData.html#instance-member-volume",
    "src/module/report/HalsteadData.js~HalsteadData#volume",
    "member"
  ],
  [
    "src/module/report/methodreport.js",
    "file/src/module/report/MethodReport.js.html",
    "src/module/report/MethodReport.js",
    "file"
  ],
  [
    "src/module/report/methodreport.js~methodreport#constructor",
    "class/src/module/report/MethodReport.js~MethodReport.html#instance-constructor-constructor",
    "src/module/report/MethodReport.js~MethodReport#constructor",
    "method"
  ],
  [
    "src/module/report/methodreport.js~methodreport#cyclomatic",
    "class/src/module/report/MethodReport.js~MethodReport.html#instance-member-cyclomatic",
    "src/module/report/MethodReport.js~MethodReport#cyclomatic",
    "member"
  ],
  [
    "src/module/report/methodreport.js~methodreport#cyclomaticdensity",
    "class/src/module/report/MethodReport.js~MethodReport.html#instance-member-cyclomaticDensity",
    "src/module/report/MethodReport.js~MethodReport#cyclomaticDensity",
    "member"
  ],
  [
    "src/module/report/methodreport.js~methodreport#finalize",
    "class/src/module/report/MethodReport.js~MethodReport.html#instance-method-finalize",
    "src/module/report/MethodReport.js~MethodReport#finalize",
    "method"
  ],
  [
    "src/module/report/methodreport.js~methodreport#halstead",
    "class/src/module/report/MethodReport.js~MethodReport.html#instance-member-halstead",
    "src/module/report/MethodReport.js~MethodReport#halstead",
    "member"
  ],
  [
    "src/module/report/methodreport.js~methodreport#lineend",
    "class/src/module/report/MethodReport.js~MethodReport.html#instance-member-lineEnd",
    "src/module/report/MethodReport.js~MethodReport#lineEnd",
    "member"
  ],
  [
    "src/module/report/methodreport.js~methodreport#linestart",
    "class/src/module/report/MethodReport.js~MethodReport.html#instance-member-lineStart",
    "src/module/report/MethodReport.js~MethodReport#lineStart",
    "member"
  ],
  [
    "src/module/report/methodreport.js~methodreport#name",
    "class/src/module/report/MethodReport.js~MethodReport.html#instance-member-name",
    "src/module/report/MethodReport.js~MethodReport#name",
    "member"
  ],
  [
    "src/module/report/methodreport.js~methodreport#params",
    "class/src/module/report/MethodReport.js~MethodReport.html#instance-member-params",
    "src/module/report/MethodReport.js~MethodReport#params",
    "member"
  ],
  [
    "src/module/report/methodreport.js~methodreport#sloc",
    "class/src/module/report/MethodReport.js~MethodReport.html#instance-member-sloc",
    "src/module/report/MethodReport.js~MethodReport#sloc",
    "member"
  ],
  [
    "src/module/report/methodreport.js~methodreport#summetrics",
    "class/src/module/report/MethodReport.js~MethodReport.html#instance-method-sumMetrics",
    "src/module/report/MethodReport.js~MethodReport#sumMetrics",
    "method"
  ],
  [
    "src/module/report/methodreport.js~methodreport.getmaintainabilitymetrics",
    "class/src/module/report/MethodReport.js~MethodReport.html#static-method-getMaintainabilityMetrics",
    "src/module/report/MethodReport.js~MethodReport.getMaintainabilityMetrics",
    "method"
  ],
  [
    "src/module/report/methodreport.js~methodreport.parse",
    "class/src/module/report/MethodReport.js~MethodReport.html#static-method-parse",
    "src/module/report/MethodReport.js~MethodReport.parse",
    "method"
  ],
  [
    "src/module/report/modulereport.js",
    "file/src/module/report/ModuleReport.js.html",
    "src/module/report/ModuleReport.js",
    "file"
  ],
  [
    "src/module/report/modulereport.js~modulereport#_scopestackclass",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-_scopeStackClass",
    "src/module/report/ModuleReport.js~ModuleReport#_scopeStackClass",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#_scopestackmethod",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-_scopeStackMethod",
    "src/module/report/ModuleReport.js~ModuleReport#_scopeStackMethod",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#adddependencies",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-method-addDependencies",
    "src/module/report/ModuleReport.js~ModuleReport#addDependencies",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport#aggregate",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-aggregate",
    "src/module/report/ModuleReport.js~ModuleReport#aggregate",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#classes",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-classes",
    "src/module/report/ModuleReport.js~ModuleReport#classes",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#constructor",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-constructor-constructor",
    "src/module/report/ModuleReport.js~ModuleReport#constructor",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport#createscope",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-method-createScope",
    "src/module/report/ModuleReport.js~ModuleReport#createScope",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport#cyclomatic",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-cyclomatic",
    "src/module/report/ModuleReport.js~ModuleReport#cyclomatic",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#dependencies",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-dependencies",
    "src/module/report/ModuleReport.js~ModuleReport#dependencies",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#effort",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-effort",
    "src/module/report/ModuleReport.js~ModuleReport#effort",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#filepath",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-filePath",
    "src/module/report/ModuleReport.js~ModuleReport#filePath",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#finalize",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-method-finalize",
    "src/module/report/ModuleReport.js~ModuleReport#finalize",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport#getcurrentclassreport",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-method-getCurrentClassReport",
    "src/module/report/ModuleReport.js~ModuleReport#getCurrentClassReport",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport#getcurrentmethodreport",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-method-getCurrentMethodReport",
    "src/module/report/ModuleReport.js~ModuleReport#getCurrentMethodReport",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport#halsteaditemencountered",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-method-halsteadItemEncountered",
    "src/module/report/ModuleReport.js~ModuleReport#halsteadItemEncountered",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport#incrementcyclomatic",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-method-incrementCyclomatic",
    "src/module/report/ModuleReport.js~ModuleReport#incrementCyclomatic",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport#incrementlogicalsloc",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-method-incrementLogicalSloc",
    "src/module/report/ModuleReport.js~ModuleReport#incrementLogicalSloc",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport#lineend",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-lineEnd",
    "src/module/report/ModuleReport.js~ModuleReport#lineEnd",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#linestart",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-lineStart",
    "src/module/report/ModuleReport.js~ModuleReport#lineStart",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#loc",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-loc",
    "src/module/report/ModuleReport.js~ModuleReport#loc",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#maintainability",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-maintainability",
    "src/module/report/ModuleReport.js~ModuleReport#maintainability",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#methods",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-methods",
    "src/module/report/ModuleReport.js~ModuleReport#methods",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#params",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-params",
    "src/module/report/ModuleReport.js~ModuleReport#params",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#popscope",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-method-popScope",
    "src/module/report/ModuleReport.js~ModuleReport#popScope",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport#processhalsteaditems",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-method-processHalsteadItems",
    "src/module/report/ModuleReport.js~ModuleReport#processHalsteadItems",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport#settings",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-settings",
    "src/module/report/ModuleReport.js~ModuleReport#settings",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#srcpath",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-srcPath",
    "src/module/report/ModuleReport.js~ModuleReport#srcPath",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#srcpathalias",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-member-srcPathAlias",
    "src/module/report/ModuleReport.js~ModuleReport#srcPathAlias",
    "member"
  ],
  [
    "src/module/report/modulereport.js~modulereport#summetrics",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#instance-method-sumMetrics",
    "src/module/report/ModuleReport.js~ModuleReport#sumMetrics",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport.getmaintainabilitymetrics",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#static-method-getMaintainabilityMetrics",
    "src/module/report/ModuleReport.js~ModuleReport.getMaintainabilityMetrics",
    "method"
  ],
  [
    "src/module/report/modulereport.js~modulereport.parse",
    "class/src/module/report/ModuleReport.js~ModuleReport.html#static-method-parse",
    "src/module/report/ModuleReport.js~ModuleReport.parse",
    "method"
  ],
  [
    "src/module/traits/halsteadarray.js",
    "file/src/module/traits/HalsteadArray.js.html",
    "src/module/traits/HalsteadArray.js",
    "file"
  ],
  [
    "src/module/traits/halsteadarray.js~halsteadarray#_data",
    "class/src/module/traits/HalsteadArray.js~HalsteadArray.html#instance-member-_data",
    "src/module/traits/HalsteadArray.js~HalsteadArray#_data",
    "member"
  ],
  [
    "src/module/traits/halsteadarray.js~halsteadarray#_metric",
    "class/src/module/traits/HalsteadArray.js~HalsteadArray.html#instance-member-_metric",
    "src/module/traits/HalsteadArray.js~HalsteadArray#_metric",
    "member"
  ],
  [
    "src/module/traits/halsteadarray.js~halsteadarray#constructor",
    "class/src/module/traits/HalsteadArray.js~HalsteadArray.html#instance-constructor-constructor",
    "src/module/traits/HalsteadArray.js~HalsteadArray#constructor",
    "method"
  ],
  [
    "src/module/traits/halsteadarray.js~halsteadarray#foreach",
    "class/src/module/traits/HalsteadArray.js~HalsteadArray.html#instance-method-forEach",
    "src/module/traits/HalsteadArray.js~HalsteadArray#forEach",
    "method"
  ],
  [
    "src/module/traits/halsteadarray.js~halsteadarray#get",
    "class/src/module/traits/HalsteadArray.js~HalsteadArray.html#instance-method-get",
    "src/module/traits/HalsteadArray.js~HalsteadArray#get",
    "method"
  ],
  [
    "src/module/traits/halsteadarray.js~halsteadarray#length",
    "class/src/module/traits/HalsteadArray.js~HalsteadArray.html#instance-get-length",
    "src/module/traits/HalsteadArray.js~HalsteadArray#length",
    "member"
  ],
  [
    "src/module/traits/halsteadarray.js~halsteadarray#metric",
    "class/src/module/traits/HalsteadArray.js~HalsteadArray.html#instance-get-metric",
    "src/module/traits/HalsteadArray.js~HalsteadArray#metric",
    "member"
  ],
  [
    "src/module/traits/halsteadarray.js~halsteadarray#type",
    "class/src/module/traits/HalsteadArray.js~HalsteadArray.html#instance-get-type",
    "src/module/traits/HalsteadArray.js~HalsteadArray#type",
    "member"
  ],
  [
    "src/module/traits/halsteadarray.js~halsteadarray#valueof",
    "class/src/module/traits/HalsteadArray.js~HalsteadArray.html#instance-method-valueOf",
    "src/module/traits/HalsteadArray.js~HalsteadArray#valueOf",
    "method"
  ],
  [
    "src/module/traits/trait.js",
    "file/src/module/traits/Trait.js.html",
    "src/module/traits/Trait.js",
    "file"
  ],
  [
    "src/module/traits/trait.js~trait#_data",
    "class/src/module/traits/Trait.js~Trait.html#instance-member-_data",
    "src/module/traits/Trait.js~Trait#_data",
    "member"
  ],
  [
    "src/module/traits/trait.js~trait#_metric",
    "class/src/module/traits/Trait.js~Trait.html#instance-member-_metric",
    "src/module/traits/Trait.js~Trait#_metric",
    "member"
  ],
  [
    "src/module/traits/trait.js~trait#constructor",
    "class/src/module/traits/Trait.js~Trait.html#instance-constructor-constructor",
    "src/module/traits/Trait.js~Trait#constructor",
    "method"
  ],
  [
    "src/module/traits/trait.js~trait#metric",
    "class/src/module/traits/Trait.js~Trait.html#instance-get-metric",
    "src/module/traits/Trait.js~Trait#metric",
    "member"
  ],
  [
    "src/module/traits/trait.js~trait#type",
    "class/src/module/traits/Trait.js~Trait.html#instance-get-type",
    "src/module/traits/Trait.js~Trait#type",
    "member"
  ],
  [
    "src/module/traits/trait.js~trait#valueof",
    "class/src/module/traits/Trait.js~Trait.html#instance-method-valueOf",
    "src/module/traits/Trait.js~Trait#valueOf",
    "method"
  ],
  [
    "src/module/traits/traithalstead.js",
    "file/src/module/traits/TraitHalstead.js.html",
    "src/module/traits/TraitHalstead.js",
    "file"
  ],
  [
    "src/module/traits/traithalstead.js~traithalstead#_data",
    "class/src/module/traits/TraitHalstead.js~TraitHalstead.html#instance-member-_data",
    "src/module/traits/TraitHalstead.js~TraitHalstead#_data",
    "member"
  ],
  [
    "src/module/traits/traithalstead.js~traithalstead#_metric",
    "class/src/module/traits/TraitHalstead.js~TraitHalstead.html#instance-member-_metric",
    "src/module/traits/TraitHalstead.js~TraitHalstead#_metric",
    "member"
  ],
  [
    "src/module/traits/traithalstead.js~traithalstead#constructor",
    "class/src/module/traits/TraitHalstead.js~TraitHalstead.html#instance-constructor-constructor",
    "src/module/traits/TraitHalstead.js~TraitHalstead#constructor",
    "method"
  ],
  [
    "src/module/traits/traithalstead.js~traithalstead#filter",
    "class/src/module/traits/TraitHalstead.js~TraitHalstead.html#instance-method-filter",
    "src/module/traits/TraitHalstead.js~TraitHalstead#filter",
    "method"
  ],
  [
    "src/module/traits/traithalstead.js~traithalstead#metric",
    "class/src/module/traits/TraitHalstead.js~TraitHalstead.html#instance-get-metric",
    "src/module/traits/TraitHalstead.js~TraitHalstead#metric",
    "member"
  ],
  [
    "src/module/traits/traithalstead.js~traithalstead#type",
    "class/src/module/traits/TraitHalstead.js~TraitHalstead.html#instance-get-type",
    "src/module/traits/TraitHalstead.js~TraitHalstead#type",
    "member"
  ],
  [
    "src/module/traits/traithalstead.js~traithalstead#valueof",
    "class/src/module/traits/TraitHalstead.js~TraitHalstead.html#instance-method-valueOf",
    "src/module/traits/TraitHalstead.js~TraitHalstead#valueOf",
    "method"
  ],
  [
    "src/module/traits/actualize.js",
    "file/src/module/traits/actualize.js.html",
    "src/module/traits/actualize.js",
    "file"
  ],
  [
    "src/module/traits/safearray.js",
    "file/src/module/traits/safeArray.js.html",
    "src/module/traits/safeArray.js",
    "file"
  ],
  [
    "src/module/traits/safename.js",
    "file/src/module/traits/safeName.js.html",
    "src/module/traits/safeName.js",
    "file"
  ],
  [
    "src/project/result/projectresult.js",
    "file/src/project/result/ProjectResult.js.html",
    "src/project/result/ProjectResult.js",
    "file"
  ],
  [
    "src/project/result/projectresult.js~projectresult#adjacencylist",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-member-adjacencyList",
    "src/project/result/ProjectResult.js~ProjectResult#adjacencyList",
    "member"
  ],
  [
    "src/project/result/projectresult.js~projectresult#changecost",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-member-changeCost",
    "src/project/result/ProjectResult.js~ProjectResult#changeCost",
    "member"
  ],
  [
    "src/project/result/projectresult.js~projectresult#constructor",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-constructor-constructor",
    "src/project/result/ProjectResult.js~ProjectResult#constructor",
    "method"
  ],
  [
    "src/project/result/projectresult.js~projectresult#coresize",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-member-coreSize",
    "src/project/result/ProjectResult.js~ProjectResult#coreSize",
    "member"
  ],
  [
    "src/project/result/projectresult.js~projectresult#cyclomatic",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-member-cyclomatic",
    "src/project/result/ProjectResult.js~ProjectResult#cyclomatic",
    "member"
  ],
  [
    "src/project/result/projectresult.js~projectresult#effort",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-member-effort",
    "src/project/result/ProjectResult.js~ProjectResult#effort",
    "member"
  ],
  [
    "src/project/result/projectresult.js~projectresult#finalize",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-method-finalize",
    "src/project/result/ProjectResult.js~ProjectResult#finalize",
    "method"
  ],
  [
    "src/project/result/projectresult.js~projectresult#firstorderdensity",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-member-firstOrderDensity",
    "src/project/result/ProjectResult.js~ProjectResult#firstOrderDensity",
    "member"
  ],
  [
    "src/project/result/projectresult.js~projectresult#loc",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-member-loc",
    "src/project/result/ProjectResult.js~ProjectResult#loc",
    "member"
  ],
  [
    "src/project/result/projectresult.js~projectresult#maintainability",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-member-maintainability",
    "src/project/result/ProjectResult.js~ProjectResult#maintainability",
    "member"
  ],
  [
    "src/project/result/projectresult.js~projectresult#params",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-member-params",
    "src/project/result/ProjectResult.js~ProjectResult#params",
    "member"
  ],
  [
    "src/project/result/projectresult.js~projectresult#reports",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-member-reports",
    "src/project/result/ProjectResult.js~ProjectResult#reports",
    "member"
  ],
  [
    "src/project/result/projectresult.js~projectresult#settings",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-member-settings",
    "src/project/result/ProjectResult.js~ProjectResult#settings",
    "member"
  ],
  [
    "src/project/result/projectresult.js~projectresult#tostringadjacency",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-method-toStringAdjacency",
    "src/project/result/ProjectResult.js~ProjectResult#toStringAdjacency",
    "method"
  ],
  [
    "src/project/result/projectresult.js~projectresult#tostringvisibility",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-method-toStringVisibility",
    "src/project/result/ProjectResult.js~ProjectResult#toStringVisibility",
    "method"
  ],
  [
    "src/project/result/projectresult.js~projectresult#visibilitylist",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#instance-member-visibilityList",
    "src/project/result/ProjectResult.js~ProjectResult#visibilityList",
    "member"
  ],
  [
    "src/project/result/projectresult.js~projectresult.parse",
    "class/src/project/result/ProjectResult.js~ProjectResult.html#static-method-parse",
    "src/project/result/ProjectResult.js~ProjectResult.parse",
    "method"
  ],
  [
    "src/utils/mathutil.js",
    "file/src/utils/MathUtil.js.html",
    "src/utils/MathUtil.js",
    "file"
  ],
  [
    "src/utils/mathutil.js~mathutil.compactmatrix",
    "class/src/utils/MathUtil.js~MathUtil.html#static-method-compactMatrix",
    "src/utils/MathUtil.js~MathUtil.compactMatrix",
    "method"
  ],
  [
    "src/utils/mathutil.js~mathutil.create2darray",
    "class/src/utils/MathUtil.js~MathUtil.html#static-method-create2DArray",
    "src/utils/MathUtil.js~MathUtil.create2DArray",
    "method"
  ],
  [
    "src/utils/mathutil.js~mathutil.getmedian",
    "class/src/utils/MathUtil.js~MathUtil.html#static-method-getMedian",
    "src/utils/MathUtil.js~MathUtil.getMedian",
    "method"
  ],
  [
    "src/utils/mathutil.js~mathutil.getpercent",
    "class/src/utils/MathUtil.js~MathUtil.html#static-method-getPercent",
    "src/utils/MathUtil.js~MathUtil.getPercent",
    "method"
  ],
  [
    "src/utils/stringutil.js",
    "file/src/utils/StringUtil.js.html",
    "src/utils/StringUtil.js",
    "file"
  ],
  [
    "src/utils/stringutil.js~stringutil.compare",
    "class/src/utils/StringUtil.js~StringUtil.html#static-method-compare",
    "src/utils/StringUtil.js~StringUtil.compare",
    "method"
  ]
]