window.esdocSearchIndex = [
  [
    "typhonjs-color-logger/src/colorlogger.js~colorlogger",
    "class/src/ColorLogger.js~ColorLogger.html",
    "<span>ColorLogger</span> <span class=\"search-result-import-path\">typhonjs-color-logger/src/ColorLogger.js</span>",
    "class"
  ],
  [
    "typhonjs-color-logger/src/tracefilter.js~tracefilter",
    "class/src/TraceFilter.js~TraceFilter.html",
    "<span>TraceFilter</span> <span class=\"search-result-import-path\">typhonjs-color-logger/src/TraceFilter.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/colorlogger.js",
    "file/src/ColorLogger.js.html",
    "src/ColorLogger.js",
    "file"
  ],
  [
    "src/colorlogger.js~colorlogger#_applyfilters",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-_applyFilters",
    "src/ColorLogger.js~ColorLogger#_applyFilters",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#_exclusivetracefilters",
    "class/src/ColorLogger.js~ColorLogger.html#instance-member-_exclusiveTraceFilters",
    "src/ColorLogger.js~ColorLogger#_exclusiveTraceFilters",
    "member"
  ],
  [
    "src/colorlogger.js~colorlogger#_inclusivetracefilters",
    "class/src/ColorLogger.js~ColorLogger.html#instance-member-_inclusiveTraceFilters",
    "src/ColorLogger.js~ColorLogger#_inclusiveTraceFilters",
    "member"
  ],
  [
    "src/colorlogger.js~colorlogger#_loglevel",
    "class/src/ColorLogger.js~ColorLogger.html#instance-member-_logLevel",
    "src/ColorLogger.js~ColorLogger#_logLevel",
    "member"
  ],
  [
    "src/colorlogger.js~colorlogger#_options",
    "class/src/ColorLogger.js~ColorLogger.html#instance-member-_options",
    "src/ColorLogger.js~ColorLogger#_options",
    "member"
  ],
  [
    "src/colorlogger.js~colorlogger#_output",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-_output",
    "src/ColorLogger.js~ColorLogger#_output",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#addfilter",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-addFilter",
    "src/ColorLogger.js~ColorLogger#addFilter",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#addfilters",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-addFilters",
    "src/ColorLogger.js~ColorLogger#addFilters",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#constructor",
    "class/src/ColorLogger.js~ColorLogger.html#instance-constructor-constructor",
    "src/ColorLogger.js~ColorLogger#constructor",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#debug",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-debug",
    "src/ColorLogger.js~ColorLogger#debug",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#debugnocolor",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-debugNoColor",
    "src/ColorLogger.js~ColorLogger#debugNoColor",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#debugraw",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-debugRaw",
    "src/ColorLogger.js~ColorLogger#debugRaw",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#error",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-error",
    "src/ColorLogger.js~ColorLogger#error",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#errornocolor",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-errorNoColor",
    "src/ColorLogger.js~ColorLogger#errorNoColor",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#errorraw",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-errorRaw",
    "src/ColorLogger.js~ColorLogger#errorRaw",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#fatal",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-fatal",
    "src/ColorLogger.js~ColorLogger#fatal",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#fatalnocolor",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-fatalNoColor",
    "src/ColorLogger.js~ColorLogger#fatalNoColor",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#fatalraw",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-fatalRaw",
    "src/ColorLogger.js~ColorLogger#fatalRaw",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#getallfilterdata",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-getAllFilterData",
    "src/ColorLogger.js~ColorLogger#getAllFilterData",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#getfilterdata",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-getFilterData",
    "src/ColorLogger.js~ColorLogger#getFilterData",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#getfilterenabled",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-getFilterEnabled",
    "src/ColorLogger.js~ColorLogger#getFilterEnabled",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#getloglevel",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-getLogLevel",
    "src/ColorLogger.js~ColorLogger#getLogLevel",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#getoptions",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-getOptions",
    "src/ColorLogger.js~ColorLogger#getOptions",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#gettraceinfo",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-getTraceInfo",
    "src/ColorLogger.js~ColorLogger#getTraceInfo",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#info",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-info",
    "src/ColorLogger.js~ColorLogger#info",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#infonocolor",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-infoNoColor",
    "src/ColorLogger.js~ColorLogger#infoNoColor",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#inforaw",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-infoRaw",
    "src/ColorLogger.js~ColorLogger#infoRaw",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#islevelenabled",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-isLevelEnabled",
    "src/ColorLogger.js~ColorLogger#isLevelEnabled",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#removeallfilters",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-removeAllFilters",
    "src/ColorLogger.js~ColorLogger#removeAllFilters",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#removefilter",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-removeFilter",
    "src/ColorLogger.js~ColorLogger#removeFilter",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#setfilterenabled",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-setFilterEnabled",
    "src/ColorLogger.js~ColorLogger#setFilterEnabled",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#setloglevel",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-setLogLevel",
    "src/ColorLogger.js~ColorLogger#setLogLevel",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#setoptions",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-setOptions",
    "src/ColorLogger.js~ColorLogger#setOptions",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#trace",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-trace",
    "src/ColorLogger.js~ColorLogger#trace",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#tracenocolor",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-traceNoColor",
    "src/ColorLogger.js~ColorLogger#traceNoColor",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#traceraw",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-traceRaw",
    "src/ColorLogger.js~ColorLogger#traceRaw",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#verbose",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-verbose",
    "src/ColorLogger.js~ColorLogger#verbose",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#verbosenocolor",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-verboseNoColor",
    "src/ColorLogger.js~ColorLogger#verboseNoColor",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#verboseraw",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-verboseRaw",
    "src/ColorLogger.js~ColorLogger#verboseRaw",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#warn",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-warn",
    "src/ColorLogger.js~ColorLogger#warn",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#warnnocolor",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-warnNoColor",
    "src/ColorLogger.js~ColorLogger#warnNoColor",
    "method"
  ],
  [
    "src/colorlogger.js~colorlogger#warnraw",
    "class/src/ColorLogger.js~ColorLogger.html#instance-method-warnRaw",
    "src/ColorLogger.js~ColorLogger#warnRaw",
    "method"
  ],
  [
    "src/tracefilter.js",
    "file/src/TraceFilter.js.html",
    "src/TraceFilter.js",
    "file"
  ],
  [
    "src/tracefilter.js~tracefilter#_enabled",
    "class/src/TraceFilter.js~TraceFilter.html#instance-member-_enabled",
    "src/TraceFilter.js~TraceFilter#_enabled",
    "member"
  ],
  [
    "src/tracefilter.js~tracefilter#_filter",
    "class/src/TraceFilter.js~TraceFilter.html#instance-member-_filter",
    "src/TraceFilter.js~TraceFilter#_filter",
    "member"
  ],
  [
    "src/tracefilter.js~tracefilter#_filterstring",
    "class/src/TraceFilter.js~TraceFilter.html#instance-member-_filterString",
    "src/TraceFilter.js~TraceFilter#_filterString",
    "member"
  ],
  [
    "src/tracefilter.js~tracefilter#_name",
    "class/src/TraceFilter.js~TraceFilter.html#instance-member-_name",
    "src/TraceFilter.js~TraceFilter#_name",
    "member"
  ],
  [
    "src/tracefilter.js~tracefilter#constructor",
    "class/src/TraceFilter.js~TraceFilter.html#instance-constructor-constructor",
    "src/TraceFilter.js~TraceFilter#constructor",
    "method"
  ],
  [
    "src/tracefilter.js~tracefilter#enabled",
    "class/src/TraceFilter.js~TraceFilter.html#instance-get-enabled",
    "src/TraceFilter.js~TraceFilter#enabled",
    "member"
  ],
  [
    "src/tracefilter.js~tracefilter#enabled",
    "class/src/TraceFilter.js~TraceFilter.html#instance-set-enabled",
    "src/TraceFilter.js~TraceFilter#enabled",
    "member"
  ],
  [
    "src/tracefilter.js~tracefilter#filter",
    "class/src/TraceFilter.js~TraceFilter.html#instance-get-filter",
    "src/TraceFilter.js~TraceFilter#filter",
    "member"
  ],
  [
    "src/tracefilter.js~tracefilter#filterstring",
    "class/src/TraceFilter.js~TraceFilter.html#instance-get-filterString",
    "src/TraceFilter.js~TraceFilter#filterString",
    "member"
  ],
  [
    "src/tracefilter.js~tracefilter#name",
    "class/src/TraceFilter.js~TraceFilter.html#instance-get-name",
    "src/TraceFilter.js~TraceFilter#name",
    "member"
  ],
  [
    "src/tracefilter.js~tracefilter#test",
    "class/src/TraceFilter.js~TraceFilter.html#instance-method-test",
    "src/TraceFilter.js~TraceFilter#test",
    "method"
  ],
  [
    "src/types/types.js",
    "file/src/types/types.js.html",
    "src/types/types.js",
    "file"
  ],
  [
    "src/types/types.js~colorloggeroptions",
    "typedef/index.html#static-typedef-ColorLoggerOptions",
    "src/types/types.js~ColorLoggerOptions",
    "typedef"
  ],
  [
    "src/types/types.js~tracefilterdata",
    "typedef/index.html#static-typedef-TraceFilterData",
    "src/types/types.js~TraceFilterData",
    "typedef"
  ]
]