window.esdocSearchIndex = [
  [
    "typhonjs-file-util/src/fileutil.js~fileutil",
    "class/src/FileUtil.js~FileUtil.html",
    "<span>FileUtil</span> <span class=\"search-result-import-path\">typhonjs-file-util/src/FileUtil.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/src/FileUtil.js.html#lineNumber12",
    "FileUtil:",
    "test"
  ],
  [
    "",
    "test-file/src/FileUtil.js.html#lineNumber36",
    "FileUtil: copy:",
    "test"
  ],
  [
    "",
    "test-file/src/FileUtil.js.html#lineNumber47",
    "FileUtil: create archive (1):",
    "test"
  ],
  [
    "",
    "test-file/src/FileUtil.js.html#lineNumber60",
    "FileUtil: create archive (2):",
    "test"
  ],
  [
    "",
    "test-file/src/FileUtil.js.html#lineNumber101",
    "FileUtil: hydrateGlobs (throws):",
    "test"
  ],
  [
    "",
    "test-file/src/FileUtil.js.html#lineNumber83",
    "FileUtil: hydrateGlobs:",
    "test"
  ],
  [
    "",
    "test-file/src/FileUtil.js.html#lineNumber29",
    "FileUtil: readLines:",
    "test"
  ],
  [
    "",
    "test-file/src/FileUtil.js.html#lineNumber14",
    "FileUtil: writeFile:",
    "test"
  ],
  [
    "src/fileutil.js",
    "test-file/src/FileUtil.js.html",
    "src/FileUtil.js",
    "testFile"
  ],
  [
    "src/fileutil.js",
    "file/src/FileUtil.js.html",
    "src/FileUtil.js",
    "file"
  ],
  [
    "src/fileutil.js~fileutil#_getarchive",
    "class/src/FileUtil.js~FileUtil.html#instance-method-_getArchive",
    "src/FileUtil.js~FileUtil#_getArchive",
    "method"
  ],
  [
    "src/fileutil.js~fileutil#_options",
    "class/src/FileUtil.js~FileUtil.html#instance-member-_options",
    "src/FileUtil.js~FileUtil#_options",
    "member"
  ],
  [
    "src/fileutil.js~fileutil#_poparchive",
    "class/src/FileUtil.js~FileUtil.html#instance-method-_popArchive",
    "src/FileUtil.js~FileUtil#_popArchive",
    "method"
  ],
  [
    "src/fileutil.js~fileutil#archivecntr",
    "class/src/FileUtil.js~FileUtil.html#instance-member-archiveCntr",
    "src/FileUtil.js~FileUtil#archiveCntr",
    "member"
  ],
  [
    "src/fileutil.js~fileutil#archivecreate",
    "class/src/FileUtil.js~FileUtil.html#instance-method-archiveCreate",
    "src/FileUtil.js~FileUtil#archiveCreate",
    "method"
  ],
  [
    "src/fileutil.js~fileutil#archivefinalize",
    "class/src/FileUtil.js~FileUtil.html#instance-method-archiveFinalize",
    "src/FileUtil.js~FileUtil#archiveFinalize",
    "method"
  ],
  [
    "src/fileutil.js~fileutil#archiverstack",
    "class/src/FileUtil.js~FileUtil.html#instance-member-archiverStack",
    "src/FileUtil.js~FileUtil#archiverStack",
    "member"
  ],
  [
    "src/fileutil.js~fileutil#constructor",
    "class/src/FileUtil.js~FileUtil.html#instance-constructor-constructor",
    "src/FileUtil.js~FileUtil#constructor",
    "method"
  ],
  [
    "src/fileutil.js~fileutil#copy",
    "class/src/FileUtil.js~FileUtil.html#instance-method-copy",
    "src/FileUtil.js~FileUtil#copy",
    "method"
  ],
  [
    "src/fileutil.js~fileutil#getoptions",
    "class/src/FileUtil.js~FileUtil.html#instance-method-getOptions",
    "src/FileUtil.js~FileUtil#getOptions",
    "method"
  ],
  [
    "src/fileutil.js~fileutil#hydrateglob",
    "class/src/FileUtil.js~FileUtil.html#instance-method-hydrateGlob",
    "src/FileUtil.js~FileUtil#hydrateGlob",
    "method"
  ],
  [
    "src/fileutil.js~fileutil#onpluginload",
    "class/src/FileUtil.js~FileUtil.html#instance-method-onPluginLoad",
    "src/FileUtil.js~FileUtil#onPluginLoad",
    "method"
  ],
  [
    "src/fileutil.js~fileutil#readlines",
    "class/src/FileUtil.js~FileUtil.html#instance-method-readLines",
    "src/FileUtil.js~FileUtil#readLines",
    "method"
  ],
  [
    "src/fileutil.js~fileutil#setoptions",
    "class/src/FileUtil.js~FileUtil.html#instance-method-setOptions",
    "src/FileUtil.js~FileUtil#setOptions",
    "method"
  ],
  [
    "src/fileutil.js~fileutil#writefile",
    "class/src/FileUtil.js~FileUtil.html#instance-method-writeFile",
    "src/FileUtil.js~FileUtil#writeFile",
    "method"
  ]
]