window.esdocSearchIndex = [
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber17",
    "",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber90",
    " AST Walker:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber95",
    " AST Walker: verify espree results",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber19",
    " initialize:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber28",
    " initialize: plugin function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber23",
    " initialize: plugin was object",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber34",
    " method invocation:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber58",
    " method invocation: plugin does not throw on proper event data",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber70",
    " method invocation: plugin has correct syntax data length",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber77",
    " method invocation: plugin has correct syntax properties",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber48",
    " method invocation: plugin passes back default settings data",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber63",
    " method invocation: plugin passes back syntax data",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber38",
    " method invocation: plugin throws on empty event data",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber43",
    " method invocation: plugin throws on empty event data",
    "test"
  ],
  [
    "escomplex-plugin-syntax-estree/src/pluginsyntaxestree.js~pluginsyntaxestree",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html",
    "<span>PluginSyntaxESTree</span> <span class=\"search-result-import-path\">escomplex-plugin-syntax-estree/src/PluginSyntaxESTree.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/pluginsyntaxestree.js",
    "file/src/PluginSyntaxESTree.js.html",
    "src/PluginSyntaxESTree.js",
    "file"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#arrayexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ArrayExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ArrayExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#arraypattern",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ArrayPattern",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ArrayPattern",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#arrowfunctionexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ArrowFunctionExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ArrowFunctionExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#assignmentexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-AssignmentExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#AssignmentExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#assignmentpattern",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-AssignmentPattern",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#AssignmentPattern",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#binaryexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-BinaryExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#BinaryExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#blockstatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-BlockStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#BlockStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#breakstatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-BreakStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#BreakStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#callexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-CallExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#CallExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#catchclause",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-CatchClause",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#CatchClause",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#classbody",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ClassBody",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ClassBody",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#classdeclaration",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ClassDeclaration",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ClassDeclaration",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#classexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ClassExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ClassExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#conditionalexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ConditionalExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ConditionalExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#continuestatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ContinueStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ContinueStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#dowhilestatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-DoWhileStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#DoWhileStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#emptystatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-EmptyStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#EmptyStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#exportalldeclaration",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ExportAllDeclaration",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ExportAllDeclaration",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#exportdefaultdeclaration",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ExportDefaultDeclaration",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ExportDefaultDeclaration",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#exportnameddeclaration",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ExportNamedDeclaration",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ExportNamedDeclaration",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#exportspecifier",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ExportSpecifier",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ExportSpecifier",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#expressionstatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ExpressionStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ExpressionStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#forinstatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ForInStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ForInStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#forofstatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ForOfStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ForOfStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#forstatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ForStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ForStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#functiondeclaration",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-FunctionDeclaration",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#FunctionDeclaration",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#functionexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-FunctionExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#FunctionExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#identifier",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-Identifier",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#Identifier",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#ifstatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-IfStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#IfStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#importdeclaration",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ImportDeclaration",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ImportDeclaration",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#importdefaultspecifier",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ImportDefaultSpecifier",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ImportDefaultSpecifier",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#importnamespacespecifier",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ImportNamespaceSpecifier",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ImportNamespaceSpecifier",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#importspecifier",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ImportSpecifier",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ImportSpecifier",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#labeledstatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-LabeledStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#LabeledStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#literal",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-Literal",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#Literal",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#logicalexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-LogicalExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#LogicalExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#memberexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-MemberExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#MemberExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#metaproperty",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-MetaProperty",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#MetaProperty",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#methoddefinition",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-MethodDefinition",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#MethodDefinition",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#newexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-NewExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#NewExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#objectexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ObjectExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ObjectExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#objectpattern",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ObjectPattern",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ObjectPattern",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#property",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-Property",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#Property",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#restelement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-RestElement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#RestElement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#returnstatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ReturnStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ReturnStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#sequenceexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-SequenceExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#SequenceExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#spreadelement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-SpreadElement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#SpreadElement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#super",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-Super",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#Super",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#switchcase",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-SwitchCase",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#SwitchCase",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#switchstatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-SwitchStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#SwitchStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#taggedtemplateexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-TaggedTemplateExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#TaggedTemplateExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#templateelement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-TemplateElement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#TemplateElement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#templateliteral",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-TemplateLiteral",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#TemplateLiteral",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#thisexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ThisExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ThisExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#throwstatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-ThrowStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#ThrowStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#trystatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-TryStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#TryStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#unaryexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-UnaryExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#UnaryExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#updateexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-UpdateExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#UpdateExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#variabledeclaration",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-VariableDeclaration",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#VariableDeclaration",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#variabledeclarator",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-VariableDeclarator",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#VariableDeclarator",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#whilestatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-WhileStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#WhileStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#withstatement",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-WithStatement",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#WithStatement",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#yieldexpression",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-YieldExpression",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#YieldExpression",
    "method"
  ],
  [
    "src/pluginsyntaxestree.js~pluginsyntaxestree#onconfigure",
    "class/src/PluginSyntaxESTree.js~PluginSyntaxESTree.html#instance-method-onConfigure",
    "src/PluginSyntaxESTree.js~PluginSyntaxESTree#onConfigure",
    "method"
  ],
  [
    "src/plugintest.js",
    "test-file/src/PluginTest.js.html",
    "src/PluginTest.js",
    "testFile"
  ]
]