window.esdocSearchIndex = [
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber17",
    "",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber19",
    " initialize:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber28",
    " initialize: plugin function onConfigure is exported",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber33",
    " initialize: plugin function onProjectEnd is exported",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber38",
    " initialize: plugin function onProjectStart is exported",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber23",
    " initialize: plugin was object",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber44",
    " method invocation:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber53",
    " method invocation: plugin does not throw on proper event data",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber58",
    " method invocation: plugin passes back syntax data",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber48",
    " method invocation: plugin throws on empty event data",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber66",
    " project results:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber78",
    " project results: Bootstraps the ESComplexProject runtime and fudges processing project results.",
    "test"
  ],
  [
    "escomplex-plugin-metrics-project/src/pluginmetricsproject.js~pluginmetricsproject",
    "class/src/PluginMetricsProject.js~PluginMetricsProject.html",
    "<span>PluginMetricsProject</span> <span class=\"search-result-import-path\">escomplex-plugin-metrics-project/src/PluginMetricsProject.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/pluginmetricsproject.js",
    "file/src/PluginMetricsProject.js.html",
    "src/PluginMetricsProject.js",
    "file"
  ],
  [
    "src/pluginmetricsproject.js~pluginmetricsproject#_calculateadjacencymatrix",
    "class/src/PluginMetricsProject.js~PluginMetricsProject.html#instance-method-_calculateAdjacencyMatrix",
    "src/PluginMetricsProject.js~PluginMetricsProject#_calculateAdjacencyMatrix",
    "method"
  ],
  [
    "src/pluginmetricsproject.js~pluginmetricsproject#_calculateaverages",
    "class/src/PluginMetricsProject.js~PluginMetricsProject.html#instance-method-_calculateAverages",
    "src/PluginMetricsProject.js~PluginMetricsProject#_calculateAverages",
    "method"
  ],
  [
    "src/pluginmetricsproject.js~pluginmetricsproject#_calculatecoresize",
    "class/src/PluginMetricsProject.js~PluginMetricsProject.html#instance-method-_calculateCoreSize",
    "src/PluginMetricsProject.js~PluginMetricsProject#_calculateCoreSize",
    "method"
  ],
  [
    "src/pluginmetricsproject.js~pluginmetricsproject#_calculatevisibilitymatrix",
    "class/src/PluginMetricsProject.js~PluginMetricsProject.html#instance-method-_calculateVisibilityMatrix",
    "src/PluginMetricsProject.js~PluginMetricsProject#_calculateVisibilityMatrix",
    "method"
  ],
  [
    "src/pluginmetricsproject.js~pluginmetricsproject#_doesdependencyexist",
    "class/src/PluginMetricsProject.js~PluginMetricsProject.html#instance-method-_doesDependencyExist",
    "src/PluginMetricsProject.js~PluginMetricsProject#_doesDependencyExist",
    "method"
  ],
  [
    "src/pluginmetricsproject.js~pluginmetricsproject#onconfigure",
    "class/src/PluginMetricsProject.js~PluginMetricsProject.html#instance-method-onConfigure",
    "src/PluginMetricsProject.js~PluginMetricsProject#onConfigure",
    "method"
  ],
  [
    "src/pluginmetricsproject.js~pluginmetricsproject#onprojectend",
    "class/src/PluginMetricsProject.js~PluginMetricsProject.html#instance-method-onProjectEnd",
    "src/PluginMetricsProject.js~PluginMetricsProject#onProjectEnd",
    "method"
  ],
  [
    "src/pluginmetricsproject.js~pluginmetricsproject#onprojectstart",
    "class/src/PluginMetricsProject.js~PluginMetricsProject.html#instance-method-onProjectStart",
    "src/PluginMetricsProject.js~PluginMetricsProject#onProjectStart",
    "method"
  ],
  [
    "src/pluginmetricsproject.js~pluginmetricsproject#settings",
    "class/src/PluginMetricsProject.js~PluginMetricsProject.html#instance-member-settings",
    "src/PluginMetricsProject.js~PluginMetricsProject#settings",
    "member"
  ],
  [
    "src/plugintest.js",
    "test-file/src/PluginTest.js.html",
    "src/PluginTest.js",
    "testFile"
  ]
]