window.esdocSearchIndex = [
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber17",
    "",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber77",
    " AST Walker:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber82",
    " AST Walker: verify espree results",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber19",
    " initialize:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber28",
    " initialize: plugin function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber23",
    " initialize: plugin was object",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber34",
    " method invocation:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber43",
    " method invocation: plugin does not throw on proper event data",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber55",
    " method invocation: plugin has correct syntax data length",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber64",
    " method invocation: plugin has correct syntax properties",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber48",
    " method invocation: plugin passes back syntax data",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber38",
    " method invocation: plugin throws on empty event data",
    "test"
  ],
  [
    "escomplex-plugin-syntax-babylon/src/pluginsyntaxbabylon.js~pluginsyntaxbabylon",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html",
    "<span>PluginSyntaxBabylon</span> <span class=\"search-result-import-path\">escomplex-plugin-syntax-babylon/src/PluginSyntaxBabylon.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/pluginsyntaxbabylon.js",
    "file/src/PluginSyntaxBabylon.js.html",
    "src/PluginSyntaxBabylon.js",
    "file"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#bindexpression",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-BindExpression",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#BindExpression",
    "method"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#booleanliteral",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-BooleanLiteral",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#BooleanLiteral",
    "method"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#classmethod",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-ClassMethod",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#ClassMethod",
    "method"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#decorator",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-Decorator",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#Decorator",
    "method"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#directive",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-Directive",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#Directive",
    "method"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#directiveliteral",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-DirectiveLiteral",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#DirectiveLiteral",
    "method"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#nullliteral",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-NullLiteral",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#NullLiteral",
    "method"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#numericliteral",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-NumericLiteral",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#NumericLiteral",
    "method"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#objectmethod",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-ObjectMethod",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#ObjectMethod",
    "method"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#objectproperty",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-ObjectProperty",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#ObjectProperty",
    "method"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#restproperty",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-RestProperty",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#RestProperty",
    "method"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#spreadproperty",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-SpreadProperty",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#SpreadProperty",
    "method"
  ],
  [
    "src/pluginsyntaxbabylon.js~pluginsyntaxbabylon#stringliteral",
    "class/src/PluginSyntaxBabylon.js~PluginSyntaxBabylon.html#instance-method-StringLiteral",
    "src/PluginSyntaxBabylon.js~PluginSyntaxBabylon#StringLiteral",
    "method"
  ],
  [
    "src/plugintest.js",
    "test-file/src/PluginTest.js.html",
    "src/PluginTest.js",
    "testFile"
  ]
]