window.esdocSearchIndex = [
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber17",
    "",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber19",
    " initialize:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber28",
    " initialize: plugin function onConfigure is exported",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber33",
    " initialize: plugin function onEnterNode is exported",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber38",
    " initialize: plugin function onExitNode is exported",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber43",
    " initialize: plugin function onModuleEnd is exported",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber48",
    " initialize: plugin function onModuleStart is exported",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber23",
    " initialize: plugin was object",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber54",
    " method invocation:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber63",
    " method invocation: plugin does not throw on proper event data",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber68",
    " method invocation: plugin passes back syntax data",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber58",
    " method invocation: plugin throws on empty event data",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber76",
    " module results:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginTest.js.html#lineNumber87",
    " module results: Bootstraps the ESComplexModule runtime and fudges traversing the AST with the Babylon trait syntaxes.",
    "test"
  ],
  [
    "escomplex-plugin-metrics-module/src/pluginmetricsmodule.js~pluginmetricsmodule",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html",
    "<span>PluginMetricsModule</span> <span class=\"search-result-import-path\">escomplex-plugin-metrics-module/src/PluginMetricsModule.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/pluginmetricsmodule.js",
    "file/src/PluginMetricsModule.js.html",
    "src/PluginMetricsModule.js",
    "file"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#calculatecyclomaticdensity",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-calculateCyclomaticDensity",
    "src/PluginMetricsModule.js~PluginMetricsModule#calculateCyclomaticDensity",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#calculatehalsteadmetrics",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-calculateHalsteadMetrics",
    "src/PluginMetricsModule.js~PluginMetricsModule#calculateHalsteadMetrics",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#calculatemaintainabilityindex",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-calculateMaintainabilityIndex",
    "src/PluginMetricsModule.js~PluginMetricsModule#calculateMaintainabilityIndex",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#calculatemetrics",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-calculateMetrics",
    "src/PluginMetricsModule.js~PluginMetricsModule#calculateMetrics",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#cleardependencies",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-member-clearDependencies",
    "src/PluginMetricsModule.js~PluginMetricsModule#clearDependencies",
    "member"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#createfunctionreport",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-createFunctionReport",
    "src/PluginMetricsModule.js~PluginMetricsModule#createFunctionReport",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#createinitialhalsteadstate",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-createInitialHalsteadState",
    "src/PluginMetricsModule.js~PluginMetricsModule#createInitialHalsteadState",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#createscope",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-createScope",
    "src/PluginMetricsModule.js~PluginMetricsModule#createScope",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#currentreport",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-member-currentReport",
    "src/PluginMetricsModule.js~PluginMetricsModule#currentReport",
    "member"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#halsteaditemencountered",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-halsteadItemEncountered",
    "src/PluginMetricsModule.js~PluginMetricsModule#halsteadItemEncountered",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#incrementcounter",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-incrementCounter",
    "src/PluginMetricsModule.js~PluginMetricsModule#incrementCounter",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#incrementcyclomatic",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-incrementCyclomatic",
    "src/PluginMetricsModule.js~PluginMetricsModule#incrementCyclomatic",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#incrementdistincthalsteaditems",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-incrementDistinctHalsteadItems",
    "src/PluginMetricsModule.js~PluginMetricsModule#incrementDistinctHalsteadItems",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#incrementhalsteaditems",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-incrementHalsteadItems",
    "src/PluginMetricsModule.js~PluginMetricsModule#incrementHalsteadItems",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#incrementhalsteadmetric",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-incrementHalsteadMetric",
    "src/PluginMetricsModule.js~PluginMetricsModule#incrementHalsteadMetric",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#incrementlogicalsloc",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-incrementLogicalSloc",
    "src/PluginMetricsModule.js~PluginMetricsModule#incrementLogicalSloc",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#incrementtotalhalsteaditems",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-incrementTotalHalsteadItems",
    "src/PluginMetricsModule.js~PluginMetricsModule#incrementTotalHalsteadItems",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#ishalsteadmetricdistinct",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-isHalsteadMetricDistinct",
    "src/PluginMetricsModule.js~PluginMetricsModule#isHalsteadMetricDistinct",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#onconfigure",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-onConfigure",
    "src/PluginMetricsModule.js~PluginMetricsModule#onConfigure",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#onenternode",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-onEnterNode",
    "src/PluginMetricsModule.js~PluginMetricsModule#onEnterNode",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#onexitnode",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-onExitNode",
    "src/PluginMetricsModule.js~PluginMetricsModule#onExitNode",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#onmoduleend",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-onModuleEnd",
    "src/PluginMetricsModule.js~PluginMetricsModule#onModuleEnd",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#onmodulestart",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-onModuleStart",
    "src/PluginMetricsModule.js~PluginMetricsModule#onModuleStart",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#popscope",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-popScope",
    "src/PluginMetricsModule.js~PluginMetricsModule#popScope",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#processcyclomatic",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-processCyclomatic",
    "src/PluginMetricsModule.js~PluginMetricsModule#processCyclomatic",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#processdependencies",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-processDependencies",
    "src/PluginMetricsModule.js~PluginMetricsModule#processDependencies",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#processhalsteadmetric",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-processHalsteadMetric",
    "src/PluginMetricsModule.js~PluginMetricsModule#processHalsteadMetric",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#processlloc",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-processLloc",
    "src/PluginMetricsModule.js~PluginMetricsModule#processLloc",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#processnode",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-processNode",
    "src/PluginMetricsModule.js~PluginMetricsModule#processNode",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#processoperands",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-processOperands",
    "src/PluginMetricsModule.js~PluginMetricsModule#processOperands",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#processoperators",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-processOperators",
    "src/PluginMetricsModule.js~PluginMetricsModule#processOperators",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#recorddistincthalsteadmetric",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-recordDistinctHalsteadMetric",
    "src/PluginMetricsModule.js~PluginMetricsModule#recordDistinctHalsteadMetric",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#report",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-member-report",
    "src/PluginMetricsModule.js~PluginMetricsModule#report",
    "member"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#scopestack",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-member-scopeStack",
    "src/PluginMetricsModule.js~PluginMetricsModule#scopeStack",
    "member"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#settings",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-member-settings",
    "src/PluginMetricsModule.js~PluginMetricsModule#settings",
    "member"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#summaintainabilitymetrics",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-method-sumMaintainabilityMetrics",
    "src/PluginMetricsModule.js~PluginMetricsModule#sumMaintainabilityMetrics",
    "method"
  ],
  [
    "src/pluginmetricsmodule.js~pluginmetricsmodule#syntaxes",
    "class/src/PluginMetricsModule.js~PluginMetricsModule.html#instance-member-syntaxes",
    "src/PluginMetricsModule.js~PluginMetricsModule#syntaxes",
    "member"
  ],
  [
    "src/plugintest.js",
    "test-file/src/PluginTest.js.html",
    "src/PluginTest.js",
    "testFile"
  ]
]