window.esdocSearchIndex = [
  [
    "typhonjs-ice-cap/src/icecap.js~icecap",
    "class/src/IceCap.js~IceCap.html",
    "<span>IceCap</span> <span class=\"search-result-import-path\">typhonjs-ice-cap/src/IceCap.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/icecap.js",
    "file/src/IceCap.js.html",
    "src/IceCap.js",
    "file"
  ],
  [
    "src/icecap.js~icecap#_$root",
    "class/src/IceCap.js~IceCap.html#instance-member-_$root",
    "src/IceCap.js~IceCap#_$root",
    "member"
  ],
  [
    "src/icecap.js~icecap#_eventbus",
    "class/src/IceCap.js~IceCap.html#instance-member-_eventbus",
    "src/IceCap.js~IceCap#_eventbus",
    "member"
  ],
  [
    "src/icecap.js~icecap#_filter",
    "class/src/IceCap.js~IceCap.html#instance-method-_filter",
    "src/IceCap.js~IceCap#_filter",
    "method"
  ],
  [
    "src/icecap.js~icecap#_html",
    "class/src/IceCap.js~IceCap.html#instance-member-_html",
    "src/IceCap.js~IceCap#_html",
    "member"
  ],
  [
    "src/icecap.js~icecap#_nodes",
    "class/src/IceCap.js~IceCap.html#instance-method-_nodes",
    "src/IceCap.js~IceCap#_nodes",
    "method"
  ],
  [
    "src/icecap.js~icecap#_options",
    "class/src/IceCap.js~IceCap.html#instance-member-_options",
    "src/IceCap.js~IceCap#_options",
    "member"
  ],
  [
    "src/icecap.js~icecap#_takehtml",
    "class/src/IceCap.js~IceCap.html#instance-method-_takeHTML",
    "src/IceCap.js~IceCap#_takeHTML",
    "method"
  ],
  [
    "src/icecap.js~icecap#attr",
    "class/src/IceCap.js~IceCap.html#instance-method-attr",
    "src/IceCap.js~IceCap#attr",
    "method"
  ],
  [
    "src/icecap.js~icecap#autoclose",
    "class/src/IceCap.js~IceCap.html#instance-get-autoClose",
    "src/IceCap.js~IceCap#autoClose",
    "member"
  ],
  [
    "src/icecap.js~icecap#autoclose",
    "class/src/IceCap.js~IceCap.html#instance-set-autoClose",
    "src/IceCap.js~IceCap#autoClose",
    "member"
  ],
  [
    "src/icecap.js~icecap#autodrop",
    "class/src/IceCap.js~IceCap.html#instance-get-autoDrop",
    "src/IceCap.js~IceCap#autoDrop",
    "member"
  ],
  [
    "src/icecap.js~icecap#autodrop",
    "class/src/IceCap.js~IceCap.html#instance-set-autoDrop",
    "src/IceCap.js~IceCap#autoDrop",
    "member"
  ],
  [
    "src/icecap.js~icecap#close",
    "class/src/IceCap.js~IceCap.html#instance-method-close",
    "src/IceCap.js~IceCap#close",
    "method"
  ],
  [
    "src/icecap.js~icecap#constructor",
    "class/src/IceCap.js~IceCap.html#instance-constructor-constructor",
    "src/IceCap.js~IceCap#constructor",
    "method"
  ],
  [
    "src/icecap.js~icecap#drop",
    "class/src/IceCap.js~IceCap.html#instance-method-drop",
    "src/IceCap.js~IceCap#drop",
    "method"
  ],
  [
    "src/icecap.js~icecap#html",
    "class/src/IceCap.js~IceCap.html#instance-get-html",
    "src/IceCap.js~IceCap#html",
    "member"
  ],
  [
    "src/icecap.js~icecap#into",
    "class/src/IceCap.js~IceCap.html#instance-method-into",
    "src/IceCap.js~IceCap#into",
    "method"
  ],
  [
    "src/icecap.js~icecap#load",
    "class/src/IceCap.js~IceCap.html#instance-method-load",
    "src/IceCap.js~IceCap#load",
    "method"
  ],
  [
    "src/icecap.js~icecap#loop",
    "class/src/IceCap.js~IceCap.html#instance-method-loop",
    "src/IceCap.js~IceCap#loop",
    "method"
  ],
  [
    "src/icecap.js~icecap#text",
    "class/src/IceCap.js~IceCap.html#instance-method-text",
    "src/IceCap.js~IceCap#text",
    "method"
  ],
  [
    "src/icecap.js~icecap.callback_load",
    "class/src/IceCap.js~IceCap.html#static-get-CALLBACK_LOAD",
    "src/IceCap.js~IceCap.CALLBACK_LOAD",
    "member"
  ],
  [
    "src/icecap.js~icecap.callback_text",
    "class/src/IceCap.js~IceCap.html#static-get-CALLBACK_TEXT",
    "src/IceCap.js~IceCap.CALLBACK_TEXT",
    "member"
  ],
  [
    "src/icecap.js~icecap.mode_append",
    "class/src/IceCap.js~IceCap.html#static-get-MODE_APPEND",
    "src/IceCap.js~IceCap.MODE_APPEND",
    "member"
  ],
  [
    "src/icecap.js~icecap.mode_prepend",
    "class/src/IceCap.js~IceCap.html#static-get-MODE_PREPEND",
    "src/IceCap.js~IceCap.MODE_PREPEND",
    "member"
  ],
  [
    "src/icecap.js~icecap.mode_remove",
    "class/src/IceCap.js~IceCap.html#static-get-MODE_REMOVE",
    "src/IceCap.js~IceCap.MODE_REMOVE",
    "member"
  ],
  [
    "src/icecap.js~icecap.mode_write",
    "class/src/IceCap.js~IceCap.html#static-get-MODE_WRITE",
    "src/IceCap.js~IceCap.MODE_WRITE",
    "member"
  ],
  [
    "src/icecap.js~icecap._debug",
    "class/src/IceCap.js~IceCap.html#static-member-_debug",
    "src/IceCap.js~IceCap._debug",
    "member"
  ],
  [
    "src/icecap.js~icecap.debug",
    "class/src/IceCap.js~IceCap.html#static-set-debug",
    "src/IceCap.js~IceCap.debug",
    "member"
  ]
]