window.esdocSearchIndex = [
  [
    "typhonjs-object-util/src/objectutil.js~objectutil",
    "class/src/ObjectUtil.js~ObjectUtil.html",
    "<span>ObjectUtil</span> <span class=\"search-result-import-path\">typhonjs-object-util/src/ObjectUtil.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber64",
    "ObjectUtil:",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber66",
    "ObjectUtil: depthTraverse:",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber76",
    "ObjectUtil: getAccessorList:",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber84",
    "ObjectUtil: safeAccess:",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber107",
    "ObjectUtil: safeAccess:",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber123",
    "ObjectUtil: safeAccess: add",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber131",
    "ObjectUtil: safeAccess: div",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber139",
    "ObjectUtil: safeAccess: mult",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber162",
    "ObjectUtil: safeAccess: no array accessor / negative number",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber155",
    "ObjectUtil: safeAccess: no array accessor / string",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber115",
    "ObjectUtil: safeAccess: set",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber147",
    "ObjectUtil: safeAccess: sub",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber96",
    "ObjectUtil: safeEqual:",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber170",
    "ObjectUtil: validate:",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber232",
    "ObjectUtil: validate: invalid return:",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber234",
    "ObjectUtil: validate: invalid return: entry (1 / false)",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber249",
    "ObjectUtil: validate: invalid return: entry|array (1 / false)",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber172",
    "ObjectUtil: validate: invalid throws:",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber174",
    "ObjectUtil: validate: invalid throws: array (1 / throws)",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber189",
    "ObjectUtil: validate: invalid throws: entry (1 / throws)",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber204",
    "ObjectUtil: validate: invalid throws: entry|array (1 / throws)",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber278",
    "ObjectUtil: validate: valid:",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber280",
    "ObjectUtil: validate: valid: array is entry (1 / false)",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber310",
    "ObjectUtil: validate: valid: entry (1 / true)",
    "test"
  ],
  [
    "",
    "test-file/src/ObjectUtil.js.html#lineNumber295",
    "ObjectUtil: validate: valid: entry is array (1 / true)",
    "test"
  ],
  [
    "src/objectutil.js",
    "file/src/ObjectUtil.js.html",
    "src/ObjectUtil.js",
    "file"
  ],
  [
    "src/objectutil.js",
    "test-file/src/ObjectUtil.js.html",
    "src/ObjectUtil.js",
    "testFile"
  ],
  [
    "src/objectutil.js~objectutil.depthtraverse",
    "class/src/ObjectUtil.js~ObjectUtil.html#static-method-depthTraverse",
    "src/ObjectUtil.js~ObjectUtil.depthTraverse",
    "method"
  ],
  [
    "src/objectutil.js~objectutil.getaccessorlist",
    "class/src/ObjectUtil.js~ObjectUtil.html#static-method-getAccessorList",
    "src/ObjectUtil.js~ObjectUtil.getAccessorList",
    "method"
  ],
  [
    "src/objectutil.js~objectutil.safeaccess",
    "class/src/ObjectUtil.js~ObjectUtil.html#static-method-safeAccess",
    "src/ObjectUtil.js~ObjectUtil.safeAccess",
    "method"
  ],
  [
    "src/objectutil.js~objectutil.safeequal",
    "class/src/ObjectUtil.js~ObjectUtil.html#static-method-safeEqual",
    "src/ObjectUtil.js~ObjectUtil.safeEqual",
    "method"
  ],
  [
    "src/objectutil.js~objectutil.safeset",
    "class/src/ObjectUtil.js~ObjectUtil.html#static-method-safeSet",
    "src/ObjectUtil.js~ObjectUtil.safeSet",
    "method"
  ],
  [
    "src/objectutil.js~objectutil.safesetall",
    "class/src/ObjectUtil.js~ObjectUtil.html#static-method-safeSetAll",
    "src/ObjectUtil.js~ObjectUtil.safeSetAll",
    "method"
  ],
  [
    "src/objectutil.js~objectutil.validate",
    "class/src/ObjectUtil.js~ObjectUtil.html#static-method-validate",
    "src/ObjectUtil.js~ObjectUtil.validate",
    "method"
  ],
  [
    "src/objectutil.js~objectutil.validatearray",
    "class/src/ObjectUtil.js~ObjectUtil.html#static-method-validateArray",
    "src/ObjectUtil.js~ObjectUtil.validateArray",
    "method"
  ],
  [
    "src/objectutil.js~objectutil.validateentry",
    "class/src/ObjectUtil.js~ObjectUtil.html#static-method-validateEntry",
    "src/ObjectUtil.js~ObjectUtil.validateEntry",
    "method"
  ],
  [
    "src/objectutil.js~objectutil.validateentryorarray",
    "class/src/ObjectUtil.js~ObjectUtil.html#static-method-validateEntryOrArray",
    "src/ObjectUtil.js~ObjectUtil.validateEntryOrArray",
    "method"
  ]
]