window.esdocSearchIndex = [
  [
    "typhonjs-escomplex/src/escomplex.js~escomplex",
    "class/src/ESComplex.js~ESComplex.html",
    "<span>ESComplex</span> <span class=\"search-result-import-path\">typhonjs-escomplex/src/ESComplex.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex/src/parser.js~parser",
    "class/src/Parser.js~Parser.html",
    "<span>Parser</span> <span class=\"search-result-import-path\">typhonjs-escomplex/src/Parser.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/escomplex.js",
    "file/src/ESComplex.js.html",
    "src/ESComplex.js",
    "file"
  ],
  [
    "src/escomplex.js~escomplex#_escomplexmodule",
    "class/src/ESComplex.js~ESComplex.html#instance-member-_escomplexModule",
    "src/ESComplex.js~ESComplex#_escomplexModule",
    "member"
  ],
  [
    "src/escomplex.js~escomplex#_escomplexproject",
    "class/src/ESComplex.js~ESComplex.html#instance-member-_escomplexProject",
    "src/ESComplex.js~ESComplex#_escomplexProject",
    "member"
  ],
  [
    "src/escomplex.js~escomplex#analyze",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyze",
    "src/ESComplex.js~ESComplex#analyze",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzeast",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeAST",
    "src/ESComplex.js~ESComplex#analyzeAST",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzeastasync",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeASTAsync",
    "src/ESComplex.js~ESComplex#analyzeASTAsync",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzeasync",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeAsync",
    "src/ESComplex.js~ESComplex#analyzeAsync",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzeproject",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeProject",
    "src/ESComplex.js~ESComplex#analyzeProject",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzeprojectast",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeProjectAST",
    "src/ESComplex.js~ESComplex#analyzeProjectAST",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzeprojectastasync",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeProjectASTAsync",
    "src/ESComplex.js~ESComplex#analyzeProjectASTAsync",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzeprojectasync",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeProjectAsync",
    "src/ESComplex.js~ESComplex#analyzeProjectAsync",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#constructor",
    "class/src/ESComplex.js~ESComplex.html#instance-constructor-constructor",
    "src/ESComplex.js~ESComplex#constructor",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#parse",
    "class/src/ESComplex.js~ESComplex.html#instance-method-parse",
    "src/ESComplex.js~ESComplex#parse",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#parseasync",
    "class/src/ESComplex.js~ESComplex.html#instance-method-parseAsync",
    "src/ESComplex.js~ESComplex#parseAsync",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#processprojectresults",
    "class/src/ESComplex.js~ESComplex.html#instance-method-processProjectResults",
    "src/ESComplex.js~ESComplex#processProjectResults",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#processprojectresultsasync",
    "class/src/ESComplex.js~ESComplex.html#instance-method-processProjectResultsAsync",
    "src/ESComplex.js~ESComplex#processProjectResultsAsync",
    "method"
  ],
  [
    "src/parser.js",
    "file/src/Parser.js.html",
    "src/Parser.js",
    "file"
  ],
  [
    "src/parser.js~parser.parse",
    "class/src/Parser.js~Parser.html#static-method-parse",
    "src/Parser.js~Parser.parse",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ]
]