window.esdocSearchIndex = [
  [
    "typhonjs-escomplex/src/escomplex.js~escomplex",
    "class/src/ESComplex.js~ESComplex.html",
    "<span>ESComplex</span> <span class=\"search-result-import-path\">typhonjs-escomplex/src/ESComplex.js</span>",
    "class"
  ],
  [
    "typhonjs-escomplex/src/parser.js~parser",
    "class/src/Parser.js~Parser.html",
    "<span>Parser</span> <span class=\"search-result-import-path\">typhonjs-escomplex/src/Parser.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/escomplex.js",
    "file/src/ESComplex.js.html",
    "src/ESComplex.js",
    "file"
  ],
  [
    "src/escomplex.js~escomplex#_escomplexmodule",
    "class/src/ESComplex.js~ESComplex.html#instance-member-_escomplexModule",
    "src/ESComplex.js~ESComplex#_escomplexModule",
    "member"
  ],
  [
    "src/escomplex.js~escomplex#_escomplexproject",
    "class/src/ESComplex.js~ESComplex.html#instance-member-_escomplexProject",
    "src/ESComplex.js~ESComplex#_escomplexProject",
    "member"
  ],
  [
    "src/escomplex.js~escomplex#analyzemodule",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeModule",
    "src/ESComplex.js~ESComplex#analyzeModule",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzemoduleast",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeModuleAST",
    "src/ESComplex.js~ESComplex#analyzeModuleAST",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzemoduleastasync",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeModuleASTAsync",
    "src/ESComplex.js~ESComplex#analyzeModuleASTAsync",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzemoduleasync",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeModuleAsync",
    "src/ESComplex.js~ESComplex#analyzeModuleAsync",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzeproject",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeProject",
    "src/ESComplex.js~ESComplex#analyzeProject",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzeprojectast",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeProjectAST",
    "src/ESComplex.js~ESComplex#analyzeProjectAST",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzeprojectastasync",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeProjectASTAsync",
    "src/ESComplex.js~ESComplex#analyzeProjectASTAsync",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#analyzeprojectasync",
    "class/src/ESComplex.js~ESComplex.html#instance-method-analyzeProjectAsync",
    "src/ESComplex.js~ESComplex#analyzeProjectAsync",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#constructor",
    "class/src/ESComplex.js~ESComplex.html#instance-constructor-constructor",
    "src/ESComplex.js~ESComplex#constructor",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#parse",
    "class/src/ESComplex.js~ESComplex.html#instance-method-parse",
    "src/ESComplex.js~ESComplex#parse",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#parseasync",
    "class/src/ESComplex.js~ESComplex.html#instance-method-parseAsync",
    "src/ESComplex.js~ESComplex#parseAsync",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#processproject",
    "class/src/ESComplex.js~ESComplex.html#instance-method-processProject",
    "src/ESComplex.js~ESComplex#processProject",
    "method"
  ],
  [
    "src/escomplex.js~escomplex#processprojectasync",
    "class/src/ESComplex.js~ESComplex.html#instance-method-processProjectAsync",
    "src/ESComplex.js~ESComplex#processProjectAsync",
    "method"
  ],
  [
    "src/parser.js",
    "file/src/Parser.js.html",
    "src/Parser.js",
    "file"
  ],
  [
    "src/parser.js~parser.parse",
    "class/src/Parser.js~Parser.html#static-method-parse",
    "src/Parser.js~Parser.parse",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index/index.js",
    "test-file/src/index/index.js.html",
    "src/index/index.js",
    "testFile"
  ],
  [
    "src/testconfig.js",
    "test-file/src/testconfig.js.html",
    "src/testconfig.js",
    "testFile"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber9",
    "typhonjs-escomplex:",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber11",
    "typhonjs-escomplex: escomplex:",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber13",
    "typhonjs-escomplex: escomplex: analyzeModule function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber18",
    "typhonjs-escomplex: escomplex: analyzeModuleAST function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber48",
    "typhonjs-escomplex: escomplex: analyzeModuleASTAsync function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber43",
    "typhonjs-escomplex: escomplex: analyzeModuleAsync function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber23",
    "typhonjs-escomplex: escomplex: analyzeProject function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber28",
    "typhonjs-escomplex: escomplex: analyzeProjectAST function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber58",
    "typhonjs-escomplex: escomplex: analyzeProjectASTAsync function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber53",
    "typhonjs-escomplex: escomplex: analyzeProjectAsync function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber33",
    "typhonjs-escomplex: escomplex: parse function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber63",
    "typhonjs-escomplex: escomplex: parseAsync function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber38",
    "typhonjs-escomplex: escomplex: processProject function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber68",
    "typhonjs-escomplex: escomplex: processProjectAsync function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber73",
    "typhonjs-escomplex: escomplex: sanity test - analyzeModule",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber81",
    "typhonjs-escomplex: escomplex: sanity test - analyzeModuleAST",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber177",
    "typhonjs-escomplex: escomplex: sanity test - analyzeModuleASTAsync",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber166",
    "typhonjs-escomplex: escomplex: sanity test - analyzeModuleAsync",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber95",
    "typhonjs-escomplex: escomplex: sanity test - analyzeProject",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber113",
    "typhonjs-escomplex: escomplex: sanity test - analyzeProjectAST",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber215",
    "typhonjs-escomplex: escomplex: sanity test - analyzeProjectASTAsync",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber194",
    "typhonjs-escomplex: escomplex: sanity test - analyzeProjectAsync",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber137",
    "typhonjs-escomplex: escomplex: sanity test - parse",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber242",
    "typhonjs-escomplex: escomplex: sanity test - parseAsync",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber146",
    "typhonjs-escomplex: escomplex: sanity test - processProject",
    "test"
  ],
  [
    "",
    "test-file/src/index/index.js.html#lineNumber254",
    "typhonjs-escomplex: escomplex: sanity test - processProjectAsync",
    "test"
  ]
]