window.esdocSearchIndex = [
  [
    "backbone-esnext-events/src/eventproxy.js~eventproxy",
    "class/src/EventProxy.js~EventProxy.html",
    "<span>EventProxy</span> <span class=\"search-result-import-path\">backbone-esnext-events/src/EventProxy.js</span>",
    "class"
  ],
  [
    "backbone-esnext-events/src/events.js~events",
    "class/src/Events.js~Events.html",
    "<span>Events</span> <span class=\"search-result-import-path\">backbone-esnext-events/src/Events.js</span>",
    "class"
  ],
  [
    "backbone-esnext-events/src/typhonevents.js~typhonevents",
    "class/src/TyphonEvents.js~TyphonEvents.html",
    "<span>TyphonEvents</span> <span class=\"search-result-import-path\">backbone-esnext-events/src/TyphonEvents.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber8",
    "EventProxy",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber19",
    "EventProxy get name",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber46",
    "EventProxy trigger (destroy)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber26",
    "EventProxy trigger (on / off)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber85",
    "EventProxy trigger (once)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber209",
    "EventProxy triggerAsync",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber229",
    "EventProxy triggerAsync (once)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber101",
    "EventProxy triggerDefer",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber118",
    "EventProxy triggerDefer (once)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber189",
    "EventProxy triggerSync (Promise)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber163",
    "EventProxy triggerSync (on / off)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber130",
    "EventProxy triggerSync-0",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber138",
    "EventProxy triggerSync-1",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber171",
    "EventProxy triggerSync-1 (once)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEventProxy.js.html#lineNumber149",
    "EventProxy triggerSync-2",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber6",
    "Events",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber12",
    "Events set / get name",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber21",
    "Events trigger",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber37",
    "Events trigger (listenTo)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber57",
    "Events trigger (listenToOnce)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber28",
    "Events trigger (once)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber252",
    "Events triggerAsync",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber297",
    "Events triggerAsync (listenTo)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber328",
    "Events triggerAsync (listenToOnce)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber272",
    "Events triggerAsync (once)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber74",
    "Events triggerDefer",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber90",
    "Events triggerDefer (listenTo)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber117",
    "Events triggerDefer (listenToOnce)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber80",
    "Events triggerDefer (once)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber232",
    "Events triggerSync (Promise)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber164",
    "Events triggerSync (on / off)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber131",
    "Events triggerSync-0",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber139",
    "Events triggerSync-1",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber190",
    "Events triggerSync-1 (listenTo)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber212",
    "Events triggerSync-1 (listenToOnce)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber172",
    "Events triggerSync-1 (once)",
    "test"
  ],
  [
    "",
    "test-file/src/TestEvents.js.html#lineNumber150",
    "Events triggerSync-2",
    "test"
  ],
  [
    "src/eventproxy.js",
    "file/src/EventProxy.js.html",
    "src/EventProxy.js",
    "file"
  ],
  [
    "src/eventproxy.js~eventproxy#_eventbus",
    "class/src/EventProxy.js~EventProxy.html#instance-member-_eventbus",
    "src/EventProxy.js~EventProxy#_eventbus",
    "member"
  ],
  [
    "src/eventproxy.js~eventproxy#_proxy",
    "class/src/EventProxy.js~EventProxy.html#instance-member-_proxy",
    "src/EventProxy.js~EventProxy#_proxy",
    "member"
  ],
  [
    "src/eventproxy.js~eventproxy#constructor",
    "class/src/EventProxy.js~EventProxy.html#instance-constructor-constructor",
    "src/EventProxy.js~EventProxy#constructor",
    "method"
  ],
  [
    "src/eventproxy.js~eventproxy#destroy",
    "class/src/EventProxy.js~EventProxy.html#instance-method-destroy",
    "src/EventProxy.js~EventProxy#destroy",
    "method"
  ],
  [
    "src/eventproxy.js~eventproxy#geteventbusname",
    "class/src/EventProxy.js~EventProxy.html#instance-method-getEventbusName",
    "src/EventProxy.js~EventProxy#getEventbusName",
    "method"
  ],
  [
    "src/eventproxy.js~eventproxy#off",
    "class/src/EventProxy.js~EventProxy.html#instance-method-off",
    "src/EventProxy.js~EventProxy#off",
    "method"
  ],
  [
    "src/eventproxy.js~eventproxy#on",
    "class/src/EventProxy.js~EventProxy.html#instance-method-on",
    "src/EventProxy.js~EventProxy#on",
    "method"
  ],
  [
    "src/eventproxy.js~eventproxy#once",
    "class/src/EventProxy.js~EventProxy.html#instance-method-once",
    "src/EventProxy.js~EventProxy#once",
    "method"
  ],
  [
    "src/eventproxy.js~eventproxy#trigger",
    "class/src/EventProxy.js~EventProxy.html#instance-method-trigger",
    "src/EventProxy.js~EventProxy#trigger",
    "method"
  ],
  [
    "src/eventproxy.js~eventproxy#triggerasync",
    "class/src/EventProxy.js~EventProxy.html#instance-method-triggerAsync",
    "src/EventProxy.js~EventProxy#triggerAsync",
    "method"
  ],
  [
    "src/eventproxy.js~eventproxy#triggerdefer",
    "class/src/EventProxy.js~EventProxy.html#instance-method-triggerDefer",
    "src/EventProxy.js~EventProxy#triggerDefer",
    "method"
  ],
  [
    "src/eventproxy.js~eventproxy#triggersync",
    "class/src/EventProxy.js~EventProxy.html#instance-method-triggerSync",
    "src/EventProxy.js~EventProxy#triggerSync",
    "method"
  ],
  [
    "src/events.js",
    "file/src/Events.js.html",
    "src/Events.js",
    "file"
  ],
  [
    "src/events.js~events#_events",
    "class/src/Events.js~Events.html#instance-member-_events",
    "src/Events.js~Events#_events",
    "member"
  ],
  [
    "src/events.js~events#bind",
    "class/src/Events.js~Events.html#instance-method-bind",
    "src/Events.js~Events#bind",
    "method"
  ],
  [
    "src/events.js~events#constructor",
    "class/src/Events.js~Events.html#instance-constructor-constructor",
    "src/Events.js~Events#constructor",
    "method"
  ],
  [
    "src/events.js~events#listento",
    "class/src/Events.js~Events.html#instance-method-listenTo",
    "src/Events.js~Events#listenTo",
    "method"
  ],
  [
    "src/events.js~events#listentoonce",
    "class/src/Events.js~Events.html#instance-method-listenToOnce",
    "src/Events.js~Events#listenToOnce",
    "method"
  ],
  [
    "src/events.js~events#off",
    "class/src/Events.js~Events.html#instance-method-off",
    "src/Events.js~Events#off",
    "method"
  ],
  [
    "src/events.js~events#on",
    "class/src/Events.js~Events.html#instance-method-on",
    "src/Events.js~Events#on",
    "method"
  ],
  [
    "src/events.js~events#once",
    "class/src/Events.js~Events.html#instance-method-once",
    "src/Events.js~Events#once",
    "method"
  ],
  [
    "src/events.js~events#stoplistening",
    "class/src/Events.js~Events.html#instance-method-stopListening",
    "src/Events.js~Events#stopListening",
    "method"
  ],
  [
    "src/events.js~events#trigger",
    "class/src/Events.js~Events.html#instance-method-trigger",
    "src/Events.js~Events#trigger",
    "method"
  ],
  [
    "src/events.js~events#unbind",
    "class/src/Events.js~Events.html#instance-method-unbind",
    "src/Events.js~Events#unbind",
    "method"
  ],
  [
    "src/testeventproxy.js",
    "test-file/src/TestEventProxy.js.html",
    "src/TestEventProxy.js",
    "testFile"
  ],
  [
    "src/testevents.js",
    "test-file/src/TestEvents.js.html",
    "src/TestEvents.js",
    "testFile"
  ],
  [
    "src/typhonevents.js",
    "file/src/TyphonEvents.js.html",
    "src/TyphonEvents.js",
    "file"
  ],
  [
    "src/typhonevents.js~typhonevents#_eventbusname",
    "class/src/TyphonEvents.js~TyphonEvents.html#instance-member-_eventbusName",
    "src/TyphonEvents.js~TyphonEvents#_eventbusName",
    "member"
  ],
  [
    "src/typhonevents.js~typhonevents#constructor",
    "class/src/TyphonEvents.js~TyphonEvents.html#instance-constructor-constructor",
    "src/TyphonEvents.js~TyphonEvents#constructor",
    "method"
  ],
  [
    "src/typhonevents.js~typhonevents#geteventbusname",
    "class/src/TyphonEvents.js~TyphonEvents.html#instance-method-getEventbusName",
    "src/TyphonEvents.js~TyphonEvents#getEventbusName",
    "method"
  ],
  [
    "src/typhonevents.js~typhonevents#seteventbusname",
    "class/src/TyphonEvents.js~TyphonEvents.html#instance-method-setEventbusName",
    "src/TyphonEvents.js~TyphonEvents#setEventbusName",
    "method"
  ],
  [
    "src/typhonevents.js~typhonevents#triggerasync",
    "class/src/TyphonEvents.js~TyphonEvents.html#instance-method-triggerAsync",
    "src/TyphonEvents.js~TyphonEvents#triggerAsync",
    "method"
  ],
  [
    "src/typhonevents.js~typhonevents#triggerdefer",
    "class/src/TyphonEvents.js~TyphonEvents.html#instance-method-triggerDefer",
    "src/TyphonEvents.js~TyphonEvents#triggerDefer",
    "method"
  ],
  [
    "src/typhonevents.js~typhonevents#triggersync",
    "class/src/TyphonEvents.js~TyphonEvents.html#instance-method-triggerSync",
    "src/TyphonEvents.js~TyphonEvents#triggerSync",
    "method"
  ]
]