window.esdocSearchIndex = [
  [
    "typhonjs-plugin-manager/src/pluginentry.js~pluginentry",
    "class/src/PluginEntry.js~PluginEntry.html",
    "<span>PluginEntry</span> <span class=\"search-result-import-path\">typhonjs-plugin-manager/src/PluginEntry.js</span>",
    "class"
  ],
  [
    "typhonjs-plugin-manager/src/pluginevent.js~pluginevent",
    "class/src/PluginEvent.js~PluginEvent.html",
    "<span>PluginEvent</span> <span class=\"search-result-import-path\">typhonjs-plugin-manager/src/PluginEvent.js</span>",
    "class"
  ],
  [
    "typhonjs-plugin-manager/src/pluginmanager.js~pluginmanager",
    "class/src/PluginManager.js~PluginManager.html",
    "<span>PluginManager</span> <span class=\"search-result-import-path\">typhonjs-plugin-manager/src/PluginManager.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber20",
    "PluginManager:",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber178",
    "PluginManager: PluginConfig is invalid",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber170",
    "PluginManager: PluginConfig is valid",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber26",
    "PluginManager: PluginManager constructor function is exported",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber216",
    "PluginManager: PluginManager get plugin / method names",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber203",
    "PluginManager: PluginManager get plugin names",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber190",
    "PluginManager: PluginManager get unique method names",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber57",
    "PluginManager: PluginManager has empty result",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber136",
    "PluginManager: PluginManager has invoked both plugins (copy)",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber100",
    "PluginManager: PluginManager has invoked both plugins (pass through)",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber148",
    "PluginManager: PluginManager has invoked one result (sync)",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber158",
    "PluginManager: PluginManager has invoked two results (sync)",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber112",
    "PluginManager: PluginManager has valid test / class result (copy)",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber77",
    "PluginManager: PluginManager has valid test / class result (pass through)",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber125",
    "PluginManager: PluginManager has valid test / object result (copy)",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber89",
    "PluginManager: PluginManager has valid test / object result (pass through)",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber31",
    "PluginManager: PluginManager instance is object",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber46",
    "PluginManager: PluginManager return undefined for createEventProxy when no eventbus is assigned",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber51",
    "PluginManager: PluginManager returns EventProxy for createEventProxy when eventbus is assigned",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber41",
    "PluginManager: PluginManager throws w/ add (no options)",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber36",
    "PluginManager: PluginManager throws when invoke is called with empty parameters",
    "test"
  ],
  [
    "",
    "test-file/src/PluginManager.js.html#lineNumber66",
    "PluginManager: PluginManager w/ plugin and missing method has empty event result",
    "test"
  ],
  [
    "src/pluginentry.js",
    "file/src/PluginEntry.js.html",
    "src/PluginEntry.js",
    "file"
  ],
  [
    "src/pluginentry.js~pluginentry#_enabled",
    "class/src/PluginEntry.js~PluginEntry.html#instance-member-_enabled",
    "src/PluginEntry.js~PluginEntry#_enabled",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#_eventproxy",
    "class/src/PluginEntry.js~PluginEntry.html#instance-member-_eventProxy",
    "src/PluginEntry.js~PluginEntry#_eventProxy",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#_instance",
    "class/src/PluginEntry.js~PluginEntry.html#instance-member-_instance",
    "src/PluginEntry.js~PluginEntry#_instance",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#_name",
    "class/src/PluginEntry.js~PluginEntry.html#instance-member-_name",
    "src/PluginEntry.js~PluginEntry#_name",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#_options",
    "class/src/PluginEntry.js~PluginEntry.html#instance-member-_options",
    "src/PluginEntry.js~PluginEntry#_options",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#_target",
    "class/src/PluginEntry.js~PluginEntry.html#instance-member-_target",
    "src/PluginEntry.js~PluginEntry#_target",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#_targetescaped",
    "class/src/PluginEntry.js~PluginEntry.html#instance-member-_targetEscaped",
    "src/PluginEntry.js~PluginEntry#_targetEscaped",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#_type",
    "class/src/PluginEntry.js~PluginEntry.html#instance-member-_type",
    "src/PluginEntry.js~PluginEntry#_type",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#constructor",
    "class/src/PluginEntry.js~PluginEntry.html#instance-constructor-constructor",
    "src/PluginEntry.js~PluginEntry#constructor",
    "method"
  ],
  [
    "src/pluginentry.js~pluginentry#enabled",
    "class/src/PluginEntry.js~PluginEntry.html#instance-get-enabled",
    "src/PluginEntry.js~PluginEntry#enabled",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#enabled",
    "class/src/PluginEntry.js~PluginEntry.html#instance-set-enabled",
    "src/PluginEntry.js~PluginEntry#enabled",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#eventproxy",
    "class/src/PluginEntry.js~PluginEntry.html#instance-get-eventProxy",
    "src/PluginEntry.js~PluginEntry#eventProxy",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#instance",
    "class/src/PluginEntry.js~PluginEntry.html#instance-get-instance",
    "src/PluginEntry.js~PluginEntry#instance",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#name",
    "class/src/PluginEntry.js~PluginEntry.html#instance-get-name",
    "src/PluginEntry.js~PluginEntry#name",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#options",
    "class/src/PluginEntry.js~PluginEntry.html#instance-get-options",
    "src/PluginEntry.js~PluginEntry#options",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#target",
    "class/src/PluginEntry.js~PluginEntry.html#instance-get-target",
    "src/PluginEntry.js~PluginEntry#target",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#targetescaped",
    "class/src/PluginEntry.js~PluginEntry.html#instance-get-targetEscaped",
    "src/PluginEntry.js~PluginEntry#targetEscaped",
    "member"
  ],
  [
    "src/pluginentry.js~pluginentry#type",
    "class/src/PluginEntry.js~PluginEntry.html#instance-get-type",
    "src/PluginEntry.js~PluginEntry#type",
    "member"
  ],
  [
    "src/pluginevent.js",
    "file/src/PluginEvent.js.html",
    "src/PluginEvent.js",
    "file"
  ],
  [
    "src/pluginevent.js~pluginevent#constructor",
    "class/src/PluginEvent.js~PluginEvent.html#instance-constructor-constructor",
    "src/PluginEvent.js~PluginEvent#constructor",
    "method"
  ],
  [
    "src/pluginevent.js~pluginevent#data",
    "class/src/PluginEvent.js~PluginEvent.html#instance-member-data",
    "src/PluginEvent.js~PluginEvent#data",
    "member"
  ],
  [
    "src/pluginevent.js~pluginevent#eventbus",
    "class/src/PluginEvent.js~PluginEvent.html#instance-member-eventbus",
    "src/PluginEvent.js~PluginEvent#eventbus",
    "member"
  ],
  [
    "src/pluginevent.js~pluginevent#extra",
    "class/src/PluginEvent.js~PluginEvent.html#instance-member-extra",
    "src/PluginEvent.js~PluginEvent#extra",
    "member"
  ],
  [
    "src/pluginevent.js~pluginevent#pluginname",
    "class/src/PluginEvent.js~PluginEvent.html#instance-member-pluginName",
    "src/PluginEvent.js~PluginEvent#pluginName",
    "member"
  ],
  [
    "src/pluginevent.js~pluginevent#pluginoptions",
    "class/src/PluginEvent.js~PluginEvent.html#instance-member-pluginOptions",
    "src/PluginEvent.js~PluginEvent#pluginOptions",
    "member"
  ],
  [
    "src/pluginmanager.js",
    "test-file/src/PluginManager.js.html",
    "src/PluginManager.js",
    "testFile"
  ],
  [
    "src/pluginmanager.js",
    "file/src/PluginManager.js.html",
    "src/PluginManager.js",
    "file"
  ],
  [
    "src/pluginmanager.js~pluginmanager#_addalleventbus",
    "class/src/PluginManager.js~PluginManager.html#instance-method-_addAllEventbus",
    "src/PluginManager.js~PluginManager#_addAllEventbus",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#_addeventbus",
    "class/src/PluginManager.js~PluginManager.html#instance-method-_addEventbus",
    "src/PluginManager.js~PluginManager#_addEventbus",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#_eventprepend",
    "class/src/PluginManager.js~PluginManager.html#instance-member-_eventPrepend",
    "src/PluginManager.js~PluginManager#_eventPrepend",
    "member"
  ],
  [
    "src/pluginmanager.js~pluginmanager#_eventbus",
    "class/src/PluginManager.js~PluginManager.html#instance-member-_eventbus",
    "src/PluginManager.js~PluginManager#_eventbus",
    "member"
  ],
  [
    "src/pluginmanager.js~pluginmanager#_extraeventdata",
    "class/src/PluginManager.js~PluginManager.html#instance-member-_extraEventData",
    "src/PluginManager.js~PluginManager#_extraEventData",
    "member"
  ],
  [
    "src/pluginmanager.js~pluginmanager#_options",
    "class/src/PluginManager.js~PluginManager.html#instance-member-_options",
    "src/PluginManager.js~PluginManager#_options",
    "member"
  ],
  [
    "src/pluginmanager.js~pluginmanager#_pluginmap",
    "class/src/PluginManager.js~PluginManager.html#instance-member-_pluginMap",
    "src/PluginManager.js~PluginManager#_pluginMap",
    "member"
  ],
  [
    "src/pluginmanager.js~pluginmanager#_removealleventbus",
    "class/src/PluginManager.js~PluginManager.html#instance-method-_removeAllEventbus",
    "src/PluginManager.js~PluginManager#_removeAllEventbus",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#_removeeventbus",
    "class/src/PluginManager.js~PluginManager.html#instance-method-_removeEventbus",
    "src/PluginManager.js~PluginManager#_removeEventbus",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#add",
    "class/src/PluginManager.js~PluginManager.html#instance-method-add",
    "src/PluginManager.js~PluginManager#add",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#addall",
    "class/src/PluginManager.js~PluginManager.html#instance-method-addAll",
    "src/PluginManager.js~PluginManager#addAll",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#constructor",
    "class/src/PluginManager.js~PluginManager.html#instance-constructor-constructor",
    "src/PluginManager.js~PluginManager#constructor",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#createeventproxy",
    "class/src/PluginManager.js~PluginManager.html#instance-method-createEventProxy",
    "src/PluginManager.js~PluginManager#createEventProxy",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#destroy",
    "class/src/PluginManager.js~PluginManager.html#instance-method-destroy",
    "src/PluginManager.js~PluginManager#destroy",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#getallplugindata",
    "class/src/PluginManager.js~PluginManager.html#instance-method-getAllPluginData",
    "src/PluginManager.js~PluginManager#getAllPluginData",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#geteventbus",
    "class/src/PluginManager.js~PluginManager.html#instance-method-getEventbus",
    "src/PluginManager.js~PluginManager#getEventbus",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#getextraeventdata",
    "class/src/PluginManager.js~PluginManager.html#instance-method-getExtraEventData",
    "src/PluginManager.js~PluginManager#getExtraEventData",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#getmethodnames",
    "class/src/PluginManager.js~PluginManager.html#instance-method-getMethodNames",
    "src/PluginManager.js~PluginManager#getMethodNames",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#getoptions",
    "class/src/PluginManager.js~PluginManager.html#instance-method-getOptions",
    "src/PluginManager.js~PluginManager#getOptions",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#getplugindata",
    "class/src/PluginManager.js~PluginManager.html#instance-method-getPluginData",
    "src/PluginManager.js~PluginManager#getPluginData",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#getpluginenabled",
    "class/src/PluginManager.js~PluginManager.html#instance-method-getPluginEnabled",
    "src/PluginManager.js~PluginManager#getPluginEnabled",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#getpluginmethodnames",
    "class/src/PluginManager.js~PluginManager.html#instance-method-getPluginMethodNames",
    "src/PluginManager.js~PluginManager#getPluginMethodNames",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#getpluginnames",
    "class/src/PluginManager.js~PluginManager.html#instance-method-getPluginNames",
    "src/PluginManager.js~PluginManager#getPluginNames",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#getpluginoptions",
    "class/src/PluginManager.js~PluginManager.html#instance-method-getPluginOptions",
    "src/PluginManager.js~PluginManager#getPluginOptions",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#getpluginsenabled",
    "class/src/PluginManager.js~PluginManager.html#instance-method-getPluginsEnabled",
    "src/PluginManager.js~PluginManager#getPluginsEnabled",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#hasmethod",
    "class/src/PluginManager.js~PluginManager.html#instance-method-hasMethod",
    "src/PluginManager.js~PluginManager#hasMethod",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#hasplugin",
    "class/src/PluginManager.js~PluginManager.html#instance-method-hasPlugin",
    "src/PluginManager.js~PluginManager#hasPlugin",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#haspluginmethod",
    "class/src/PluginManager.js~PluginManager.html#instance-method-hasPluginMethod",
    "src/PluginManager.js~PluginManager#hasPluginMethod",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#invokeasync",
    "class/src/PluginManager.js~PluginManager.html#instance-method-invokeAsync",
    "src/PluginManager.js~PluginManager#invokeAsync",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#invokesync",
    "class/src/PluginManager.js~PluginManager.html#instance-method-invokeSync",
    "src/PluginManager.js~PluginManager#invokeSync",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#invokesyncevent",
    "class/src/PluginManager.js~PluginManager.html#instance-method-invokeSyncEvent",
    "src/PluginManager.js~PluginManager#invokeSyncEvent",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#isvalidconfig",
    "class/src/PluginManager.js~PluginManager.html#instance-method-isValidConfig",
    "src/PluginManager.js~PluginManager#isValidConfig",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#remove",
    "class/src/PluginManager.js~PluginManager.html#instance-method-remove",
    "src/PluginManager.js~PluginManager#remove",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#removeall",
    "class/src/PluginManager.js~PluginManager.html#instance-method-removeAll",
    "src/PluginManager.js~PluginManager#removeAll",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#seteventbus",
    "class/src/PluginManager.js~PluginManager.html#instance-method-setEventbus",
    "src/PluginManager.js~PluginManager#setEventbus",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#setextraeventdata",
    "class/src/PluginManager.js~PluginManager.html#instance-method-setExtraEventData",
    "src/PluginManager.js~PluginManager#setExtraEventData",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#setoptions",
    "class/src/PluginManager.js~PluginManager.html#instance-method-setOptions",
    "src/PluginManager.js~PluginManager#setOptions",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#setpluginenabled",
    "class/src/PluginManager.js~PluginManager.html#instance-method-setPluginEnabled",
    "src/PluginManager.js~PluginManager#setPluginEnabled",
    "method"
  ],
  [
    "src/pluginmanager.js~pluginmanager#setpluginsenabled",
    "class/src/PluginManager.js~PluginManager.html#instance-method-setPluginsEnabled",
    "src/PluginManager.js~PluginManager#setPluginsEnabled",
    "method"
  ],
  [
    "src/types/types.js",
    "file/src/types/types.js.html",
    "src/types/types.js",
    "file"
  ],
  [
    "src/types/types.js~eventproxy",
    "external/index.html",
    "src/types/types.js~EventProxy",
    "external"
  ],
  [
    "src/types/types.js~pluginconfig",
    "typedef/index.html#static-typedef-PluginConfig",
    "src/types/types.js~PluginConfig",
    "typedef"
  ],
  [
    "src/types/types.js~plugindata",
    "typedef/index.html#static-typedef-PluginData",
    "src/types/types.js~PluginData",
    "typedef"
  ],
  [
    "src/types/types.js~pluginmanageroptions",
    "typedef/index.html#static-typedef-PluginManagerOptions",
    "src/types/types.js~PluginManagerOptions",
    "typedef"
  ],
  [
    "src/types/types.js~typhonevents",
    "external/index.html",
    "src/types/types.js~TyphonEvents",
    "external"
  ]
]